System.out.println("getPercent")
if(getPercent != null)
	throw new Exception("getPercent already defined!")
val getPercent: java.lang.Double = callback("getPercent")
val getPercentType = getPercent.getClass()
System.out.println(getPercentType)
System.out.println(getPercent)
if(getPercentType != classOf[java.lang.Double])
	throw new Exception("getPercent not Double!")
callback("setPercent",getPercent)

System.out.println("getPercentVector")
if(getPercentVector != null)
	throw new Exception("getPercentVector already defined!")
val getPercentVector: Array[Double] = callback("getPercentVector")
val getPercentVectorType = getPercentVector(0).getClass()
System.out.println(getPercentVectorType)
System.out.println(getPercentVector)
if(getPercentVectorType != classOf[Double])
	throw new Exception("getPercentVector not Double!")
callback("setPercentVector",getPercentVector)

System.out.println("getPercentVectorAsList")
if(getPercentVectorAsList != null)
	throw new Exception("getPercentVectorAsList already defined!")
val getPercentVectorAsList: Array[Double] = callback("getPercentVectorAsList")
val getPercentVectorAsListType = getPercentVectorAsList(0).getClass()
System.out.println(getPercentVectorAsListType)
System.out.println(getPercentVectorAsList)
if(getPercentVectorAsListType != classOf[Double])
	throw new Exception("getPercentVectorAsList not Double!")
callback("setPercentVectorAsList",getPercentVectorAsList)

System.out.println("getPercentMatrix")
if(getPercentMatrix != null)
	throw new Exception("getPercentMatrix already defined!")
val getPercentMatrix: Array[Array[Double]] = callback("getPercentMatrix")
val getPercentMatrixType = getPercentMatrix(0)(0).getClass()
System.out.println(getPercentMatrixType)
System.out.println(getPercentMatrix)
if(getPercentMatrixType != classOf[Double])
	throw new Exception("getPercentMatrix not Double!")
callback("setPercentMatrix",getPercentMatrix)

System.out.println("getPercentMatrixAsList")
if(getPercentMatrixAsList != null)
	throw new Exception("getPercentMatrixAsList already defined!")
val getPercentMatrixAsList: Array[Array[Double]] = callback("getPercentMatrixAsList")
val getPercentMatrixAsListType = getPercentMatrixAsList(0)(0).getClass()
System.out.println(getPercentMatrixAsListType)
System.out.println(getPercentMatrixAsList)
if(getPercentMatrixAsListType != classOf[Double])
	throw new Exception("getPercentMatrixAsList not Double!")
callback("setPercentMatrixAsList",getPercentMatrixAsList)
