System.out.println("getDecimal")
if(getDecimal != null)
	throw new Exception("getDecimal already defined!")
val getDecimal: java.lang.Double = callback("getDecimal")
val getDecimalType = getDecimal.getClass()
System.out.println(getDecimalType)
System.out.println(getDecimal)
if(getDecimalType != classOf[java.lang.Double])
	throw new Exception("getDecimal not Double!")
callback[Unit]("setDecimal",getDecimal)

System.out.println("getDecimalVector")
if(getDecimalVector != null)
	throw new Exception("getDecimalVector already defined!")
val getDecimalVector: Array[Double] = callback("getDecimalVector")
val getDecimalVectorType = getDecimalVector(0).getClass()
System.out.println(getDecimalVectorType)
System.out.println(getDecimalVector)
if(getDecimalVectorType != classOf[Double])
	throw new Exception("getDecimalVector not Double!")
callback[Unit]("setDecimalVector",getDecimalVector)

System.out.println("getDecimalVectorAsList")
if(getDecimalVectorAsList != null)
	throw new Exception("getDecimalVectorAsList already defined!")
val getDecimalVectorAsList: Array[Double] = callback("getDecimalVectorAsList")
val getDecimalVectorAsListType = getDecimalVectorAsList(0).getClass()
System.out.println(getDecimalVectorAsListType)
System.out.println(getDecimalVectorAsList)
if(getDecimalVectorAsListType != classOf[Double])
	throw new Exception("getDecimalVectorAsList not Double!")
callback[Unit]("setDecimalVectorAsList",getDecimalVectorAsList)

System.out.println("getDecimalMatrix")
if(getDecimalMatrix != null)
	throw new Exception("getDecimalMatrix already defined!")
val getDecimalMatrix: Array[Array[Double]] = callback("getDecimalMatrix")
val getDecimalMatrixType = getDecimalMatrix(0)(0).getClass()
System.out.println(getDecimalMatrixType)
System.out.println(getDecimalMatrix)
if(getDecimalMatrixType != classOf[Double])
	throw new Exception("getDecimalMatrix not Double!")
callback[Unit]("setDecimalMatrix",getDecimalMatrix)

System.out.println("getDecimalMatrixAsList")
if(getDecimalMatrixAsList != null)
	throw new Exception("getDecimalMatrixAsList already defined!")
val getDecimalMatrixAsList: Array[Array[Double]] = callback("getDecimalMatrixAsList")
val getDecimalMatrixAsListType = getDecimalMatrixAsList(0)(0).getClass()
System.out.println(getDecimalMatrixAsListType)
System.out.println(getDecimalMatrixAsList)
if(getDecimalMatrixAsListType != classOf[Double])
	throw new Exception("getDecimalMatrixAsList not Double!")
callback[Unit]("setDecimalMatrixAsList",getDecimalMatrixAsList)
