System.out.println("getLong")
if(getLong != null)
	throw new Exception("getLong already defined!")
val getLong: Long = callback("getLong")
val getLongType = getLong.getClass()
System.out.println(getLongType)
System.out.println(getLong)
if(getLongType != classOf[java.lang.Long])
	throw new Exception("getLong not Long!")
callback[Unit]("setLong",getLong)

System.out.println("getLongVector")
if(getLongVector != null)
	throw new Exception("getLongVector already defined!")
val getLongVector: Array[Long] = callback("getLongVector")
val getLongVectorType = getLongVector(0).getClass()
System.out.println(getLongVectorType)
System.out.println(getLongVector)
if(getLongVectorType != classOf[Long])
	throw new Exception("getLongVector not Long!")
callback[Unit]("setLongVector",getLongVector)

System.out.println("getLongVectorAsList")
if(getLongVectorAsList != null)
	throw new Exception("getLongVectorAsList already defined!")
val getLongVectorAsList: Array[Long] = callback("getLongVectorAsList")
val getLongVectorAsListType = getLongVectorAsList(0).getClass()
System.out.println(getLongVectorAsListType)
System.out.println(getLongVectorAsList)
if(getLongVectorAsListType != classOf[Long])
	throw new Exception("getLongVectorAsList not Long!")
callback[Unit]("setLongVectorAsList",getLongVectorAsList)

System.out.println("getLongMatrix")
if(getLongMatrix != null)
	throw new Exception("getLongMatrix already defined!")
val getLongMatrix: Array[Array[Long]] = callback("getLongMatrix")
val getLongMatrixType = getLongMatrix(0)(0).getClass()
System.out.println(getLongMatrixType)
System.out.println(getLongMatrix)
if(getLongMatrixType != classOf[Long])
	throw new Exception("getLongMatrix not Long!")
callback[Unit]("setLongMatrix",getLongMatrix)

System.out.println("getLongMatrixAsList")
if(getLongMatrixAsList != null)
	throw new Exception("getLongMatrixAsList already defined!")
val getLongMatrixAsList: Array[Array[Long]] = callback("getLongMatrixAsList")
val getLongMatrixAsListType = getLongMatrixAsList(0)(0).getClass()
System.out.println(getLongMatrixAsListType)
System.out.println(getLongMatrixAsList)
if(getLongMatrixAsListType != classOf[Long])
	throw new Exception("getLongMatrixAsList not Long!")
callback[Unit]("setLongMatrixAsList",getLongMatrixAsList)
