println("getBoolean")
if(binding.containsKey("getBoolean"))
	throw Exception("getBoolean already defined!")
val getBoolean: Boolean = callback("getBoolean")
val getBooleanType = getBoolean::class
println(getBooleanType)
println(getBoolean)
if(getBooleanType != Boolean::class)
	throw Exception("getBoolean not Boolean!")
callback<Unit>("setBoolean",getBoolean)

println("getBooleanVector")
if(binding.containsKey("getBooleanVector"))
	throw Exception("getBooleanVector already defined!")
val getBooleanVector: BooleanArray = callback("getBooleanVector")
val getBooleanVectorType = getBooleanVector[0]::class
println(getBooleanVectorType)
println(getBooleanVector)
if(getBooleanVectorType != Boolean::class)
	throw Exception("getBooleanVector not Boolean!")
callback<Unit>("setBooleanVector",getBooleanVector)

println("getBooleanVectorAsList")
if(binding.containsKey("getBooleanVectorAsList"))
	throw Exception("getBooleanVectorAsList already defined!")
val getBooleanVectorAsList: BooleanArray = callback("getBooleanVectorAsList")
val getBooleanVectorAsListType = getBooleanVectorAsList[0]::class
println(getBooleanVectorAsListType)
println(getBooleanVectorAsList)
if(getBooleanVectorAsListType != Boolean::class)
	throw Exception("getBooleanVectorAsList not Boolean!")
callback<Unit>("setBooleanVectorAsList",getBooleanVectorAsList)

println("getBooleanMatrix")
if(binding.containsKey("getBooleanMatrix"))
	throw Exception("getBooleanMatrix already defined!")
val getBooleanMatrix: Array<BooleanArray> = callback("getBooleanMatrix")
val getBooleanMatrixType = getBooleanMatrix[0][0]::class
println(getBooleanMatrixType)
println(getBooleanMatrix)
if(getBooleanMatrixType != Boolean::class)
	throw Exception("getBooleanMatrix not Boolean!")
callback<Unit>("setBooleanMatrix",getBooleanMatrix)

println("getBooleanMatrixAsList")
if(binding.containsKey("getBooleanMatrixAsList"))
	throw Exception("getBooleanMatrixAsList already defined!")
val getBooleanMatrixAsList: Array<BooleanArray> = callback("getBooleanMatrixAsList")
val getBooleanMatrixAsListType = getBooleanMatrixAsList[0][0]::class
println(getBooleanMatrixAsListType)
println(getBooleanMatrixAsList)
if(getBooleanMatrixAsListType != Boolean::class)
	throw Exception("getBooleanMatrixAsList not Boolean!")
callback<Unit>("setBooleanMatrixAsList",getBooleanMatrixAsList)
