println("getByte")
if(bindings.containsKey("getByte"))
	throw Exception("getByte already defined!")
val getByte = callback("getByte")
val getByteType = getByte::class
println(getByteType)
println(getByte)
if(getByteType != Byte::class)
	throw Exception("getByte not Byte!")
callback("setByte",getByte)

println("getByteVector")
if(bindings.containsKey("getByteVector"))
	throw Exception("getByteVector already defined!")
val getByteVector = callback("getByteVector")
val getByteVectorType = getByteVector[0]::class
println(getByteVectorType)
println(getByteVector)
if(getByteVectorType != Byte::class)
	throw Exception("getByteVector not Byte!")
callback("setByteVector",getByteVector)

println("getByteVectorAsList")
if(bindings.containsKey("getByteVectorAsList"))
	throw Exception("getByteVectorAsList already defined!")
val getByteVectorAsList = callback("getByteVectorAsList")
val getByteVectorAsListType = getByteVectorAsList[0]::class
println(getByteVectorAsListType)
println(getByteVectorAsList)
if(getByteVectorAsListType != Byte::class)
	throw Exception("getByteVectorAsList not Byte!")
callback("setByteVectorAsList",getByteVectorAsList)

println("getByteMatrix")
if(bindings.containsKey("getByteMatrix"))
	throw Exception("getByteMatrix already defined!")
val getByteMatrix = callback("getByteMatrix")
val getByteMatrixType = getByteMatrix[0][0]::class
println(getByteMatrixType)
println(getByteMatrix)
if(getByteMatrixType != Byte::class)
	throw Exception("getByteMatrix not Byte!")
callback("setByteMatrix",getByteMatrix)

println("getByteMatrixAsList")
if(bindings.containsKey("getByteMatrixAsList"))
	throw Exception("getByteMatrixAsList already defined!")
val getByteMatrixAsList = callback("getByteMatrixAsList")
val getByteMatrixAsListType = getByteMatrixAsList[0][0]::class
println(getByteMatrixAsListType)
println(getByteMatrixAsList)
if(getByteMatrixAsListType != Byte::class)
	throw Exception("getByteMatrixAsList not Byte!")
callback("setByteMatrixAsList",getByteMatrixAsList)
