println("getPercent")
if(binding.containsKey("getPercent"))
	throw Exception("getPercent already defined!")
val getPercent: Double = callback("getPercent")
val getPercentType = getPercent::class
println(getPercentType)
println(getPercent)
if(getPercentType != Double::class)
	throw Exception("getPercent not Double!")
callback<Unit>("setPercent",getPercent)

println("getPercentVector")
if(binding.containsKey("getPercentVector"))
	throw Exception("getPercentVector already defined!")
val getPercentVector: DoubleArray = callback("getPercentVector")
val getPercentVectorType = getPercentVector[0]::class
println(getPercentVectorType)
println(getPercentVector)
if(getPercentVectorType != Double::class)
	throw Exception("getPercentVector not Double!")
callback<Unit>("setPercentVector",getPercentVector)

println("getPercentVectorAsList")
if(binding.containsKey("getPercentVectorAsList"))
	throw Exception("getPercentVectorAsList already defined!")
val getPercentVectorAsList: DoubleArray = callback("getPercentVectorAsList")
val getPercentVectorAsListType = getPercentVectorAsList[0]::class
println(getPercentVectorAsListType)
println(getPercentVectorAsList)
if(getPercentVectorAsListType != Double::class)
	throw Exception("getPercentVectorAsList not Double!")
callback<Unit>("setPercentVectorAsList",getPercentVectorAsList)

println("getPercentMatrix")
if(binding.containsKey("getPercentMatrix"))
	throw Exception("getPercentMatrix already defined!")
val getPercentMatrix: Array<DoubleArray> = callback("getPercentMatrix")
val getPercentMatrixType = getPercentMatrix[0][0]::class
println(getPercentMatrixType)
println(getPercentMatrix)
if(getPercentMatrixType != Double::class)
	throw Exception("getPercentMatrix not Double!")
callback<Unit>("setPercentMatrix",getPercentMatrix)

println("getPercentMatrixAsList")
if(binding.containsKey("getPercentMatrixAsList"))
	throw Exception("getPercentMatrixAsList already defined!")
val getPercentMatrixAsList: Array<DoubleArray> = callback("getPercentMatrixAsList")
val getPercentMatrixAsListType = getPercentMatrixAsList[0][0]::class
println(getPercentMatrixAsListType)
println(getPercentMatrixAsList)
if(getPercentMatrixAsListType != Double::class)
	throw Exception("getPercentMatrixAsList not Double!")
callback<Unit>("setPercentMatrixAsList",getPercentMatrixAsList)
