println("getCharacter")
if(binding.containsKey("getCharacter"))
	throw Exception("getCharacter already defined!")
val getCharacter: Char = callback("getCharacter")
val getCharacterType = getCharacter::class
println(getCharacterType)
println(getCharacter)
if(getCharacterType != Character::class)
	throw Exception("getCharacter not Character!")
callback<Unit>("setCharacter",getCharacter)

println("getCharacterVector")
if(binding.containsKey("getCharacterVector"))
	throw Exception("getCharacterVector already defined!")
val getCharacterVector: CharArray = callback("getCharacterVector")
val getCharacterVectorType = getCharacterVector[0]::class
println(getCharacterVectorType)
println(getCharacterVector)
if(getCharacterVectorType != Character::class)
	throw Exception("getCharacterVector not Character!")
callback<Unit>("setCharacterVector",getCharacterVector)

println("getCharacterVectorAsList")
if(binding.containsKey("getCharacterVectorAsList"))
	throw Exception("getCharacterVectorAsList already defined!")
val getCharacterVectorAsList: CharArray = callback("getCharacterVectorAsList")
val getCharacterVectorAsListType = getCharacterVectorAsList[0]::class
println(getCharacterVectorAsListType)
println(getCharacterVectorAsList)
if(getCharacterVectorAsListType != Character::class)
	throw Exception("getCharacterVectorAsList not Character!")
callback<Unit>("setCharacterVectorAsList",getCharacterVectorAsList)

println("getCharacterMatrix")
if(binding.containsKey("getCharacterMatrix"))
	throw Exception("getCharacterMatrix already defined!")
val getCharacterMatrix: Array<CharArray> = callback("getCharacterMatrix")
val getCharacterMatrixType = getCharacterMatrix[0][0]::class
println(getCharacterMatrixType)
println(getCharacterMatrix)
if(getCharacterMatrixType != Character::class)
	throw Exception("getCharacterMatrix not Character!")
callback<Unit>("setCharacterMatrix",getCharacterMatrix)

println("getCharacterMatrixAsList")
if(binding.containsKey("getCharacterMatrixAsList"))
	throw Exception("getCharacterMatrixAsList already defined!")
val getCharacterMatrixAsList: Array<CharArray> = callback("getCharacterMatrixAsList")
val getCharacterMatrixAsListType = getCharacterMatrixAsList[0][0]::class
println(getCharacterMatrixAsListType)
println(getCharacterMatrixAsList)
if(getCharacterMatrixAsListType != Character::class)
	throw Exception("getCharacterMatrixAsList not Character!")
callback<Unit>("setCharacterMatrixAsList",getCharacterMatrixAsList)
	