println("getShort")
if(bindings.containsKey("getShort"))
	throw Exception("getShort already defined!")
val getShort = callback("getShort")
val getShortType = getShort::class
println(getShortType)
println(getShort)
if(getShortType != Short::class)
	throw Exception("getShort not Short!")
callback("setShort",getShort)

println("getShortVector")
if(bindings.containsKey("getShortVector"))
	throw Exception("getShortVector already defined!")
val getShortVector = callback("getShortVector")
val getShortVectorType = getShortVector[0]::class
println(getShortVectorType)
println(getShortVector)
if(getShortVectorType != Short::class)
	throw Exception("getShortVector not Short!")
callback("setShortVector",getShortVector)

println("getShortVectorAsList")
if(bindings.containsKey("getShortVectorAsList"))
	throw Exception("getShortVectorAsList already defined!")
val getShortVectorAsList = callback("getShortVectorAsList")
val getShortVectorAsListType = getShortVectorAsList[0]::class
println(getShortVectorAsListType)
println(getShortVectorAsList)
if(getShortVectorAsListType != Short::class)
	throw Exception("getShortVectorAsList not Short!")
callback("setShortVectorAsList",getShortVectorAsList)

println("getShortMatrix")
if(bindings.containsKey("getShortMatrix"))
	throw Exception("getShortMatrix already defined!")
val getShortMatrix = callback("getShortMatrix")
val getShortMatrixType = getShortMatrix[0][0]::class
println(getShortMatrixType)
println(getShortMatrix)
if(getShortMatrixType != Short::class)
	throw Exception("getShortMatrix not Short!")
callback("setShortMatrix",getShortMatrix)

println("getShortMatrixAsList")
if(bindings.containsKey("getShortMatrixAsList"))
	throw Exception("getShortMatrixAsList already defined!")
val getShortMatrixAsList = callback("getShortMatrixAsList")
val getShortMatrixAsListType = getShortMatrixAsList[0][0]::class
println(getShortMatrixAsListType)
println(getShortMatrixAsList)
if(getShortMatrixAsListType != Short::class)
	throw Exception("getShortMatrixAsList not Short!")
callback("setShortMatrixAsList",getShortMatrixAsList)
