println("getDouble")
if(bindings.containsKey("getDouble"))
	throw Exception("getDouble already defined!")
val getDouble = callback("getDouble")
val getDoubleType = getDouble::class
println(getDoubleType)
println(getDouble)
if(getDoubleType != Double::class)
	throw Exception("getDouble not Double!")
callback("setDouble",getDouble)

println("getDoubleVector")
if(bindings.containsKey("getDoubleVector"))
	throw Exception("getDoubleVector already defined!")
val getDoubleVector = callback("getDoubleVector")
val getDoubleVectorType = getDoubleVector[0]::class
println(getDoubleVectorType)
println(getDoubleVector)
if(getDoubleVectorType != Double::class)
	throw Exception("getDoubleVector not Double!")
callback("setDoubleVector",getDoubleVector)

println("getDoubleVectorAsList")
if(bindings.containsKey("getDoubleVectorAsList"))
	throw Exception("getDoubleVectorAsList already defined!")
val getDoubleVectorAsList = callback("getDoubleVectorAsList")
val getDoubleVectorAsListType = getDoubleVectorAsList[0]::class
println(getDoubleVectorAsListType)
println(getDoubleVectorAsList)
if(getDoubleVectorAsListType != Double::class)
	throw Exception("getDoubleVectorAsList not Double!")
callback("setDoubleVectorAsList",getDoubleVectorAsList)

println("getDoubleMatrix")
if(bindings.containsKey("getDoubleMatrix"))
	throw Exception("getDoubleMatrix already defined!")
val getDoubleMatrix = callback("getDoubleMatrix")
val getDoubleMatrixType = getDoubleMatrix[0][0]::class
println(getDoubleMatrixType)
println(getDoubleMatrix)
if(getDoubleMatrixType != Double::class)
	throw Exception("getDoubleMatrix not Double!")
callback("setDoubleMatrix",getDoubleMatrix)

println("getDoubleMatrixAsList")
if(bindings.containsKey("getDoubleMatrixAsList"))
	throw Exception("getDoubleMatrixAsList already defined!")
val getDoubleMatrixAsList = callback("getDoubleMatrixAsList")
val getDoubleMatrixAsListType = getDoubleMatrixAsList[0][0]::class
println(getDoubleMatrixAsListType)
println(getDoubleMatrixAsList)
if(getDoubleMatrixAsListType != Double::class)
	throw Exception("getDoubleMatrixAsList not Double!")
callback("setDoubleMatrixAsList",getDoubleMatrixAsList)
