println("getFloat")
if(bindings.containsKey("getFloat"))
	throw Exception("getFloat already defined!")
val getFloat = callback("getFloat")
val getFloatType = getFloat::class
println(getFloatType)
println(getFloat)
if(getFloatType != Float::class)
	throw Exception("getFloat not Float!")
callback("setFloat",getFloat)

println("getFloatVector")
if(bindings.containsKey("getFloatVector"))
	throw Exception("getFloatVector already defined!")
val getFloatVector = callback("getFloatVector")
val getFloatVectorType = getFloatVector[0]::class
println(getFloatVectorType)
println(getFloatVector)
if(getFloatVectorType != Float::class)
	throw Exception("getFloatVector not Float!")
callback("setFloatVector",getFloatVector)

println("getFloatVectorAsList")
if(bindings.containsKey("getFloatVectorAsList"))
	throw Exception("getFloatVectorAsList already defined!")
val getFloatVectorAsList = callback("getFloatVectorAsList")
val getFloatVectorAsListType = getFloatVectorAsList[0]::class
println(getFloatVectorAsListType)
println(getFloatVectorAsList)
if(getFloatVectorAsListType != Float::class)
	throw Exception("getFloatVectorAsList not Float!")
callback("setFloatVectorAsList",getFloatVectorAsList)

println("getFloatMatrix")
if(bindings.containsKey("getFloatMatrix"))
	throw Exception("getFloatMatrix already defined!")
val getFloatMatrix = callback("getFloatMatrix")
val getFloatMatrixType = getFloatMatrix[0][0]::class
println(getFloatMatrixType)
println(getFloatMatrix)
if(getFloatMatrixType != Float::class)
	throw Exception("getFloatMatrix not Float!")
callback("setFloatMatrix",getFloatMatrix)

println("getFloatMatrixAsList")
if(bindings.containsKey("getFloatMatrixAsList"))
	throw Exception("getFloatMatrixAsList already defined!")
val getFloatMatrixAsList = callback("getFloatMatrixAsList")
val getFloatMatrixAsListType = getFloatMatrixAsList[0][0]::class
println(getFloatMatrixAsListType)
println(getFloatMatrixAsList)
if(getFloatMatrixAsListType != Float::class)
	throw Exception("getFloatMatrixAsList not Float!")
callback("setFloatMatrixAsList",getFloatMatrixAsList)
