val getBooleanVector = callback("getBooleanVector")
if(getBooleanVector != null)
	throw Exception("getBooleanVector not null!")
callback("setBooleanVector",getBooleanVector)
val getBooleanVectorAsList = callback("getBooleanVectorAsList")
if(getBooleanVectorAsList != null)
	throw Exception("getBooleanVectorAsList not null!")
callback("setBooleanVectorAsList",getBooleanVectorAsList)
val getBooleanMatrix = callback("getBooleanMatrix")
if(getBooleanMatrix != null)
	throw Exception("getBooleanMatrix not null!")
callback("setBooleanMatrix",getBooleanMatrix)
val getBooleanMatrixAsList = callback("getBooleanMatrixAsList")
if(getBooleanMatrixAsList != null)
	throw Exception("getBooleanMatrixAsList not null!")
callback("setBooleanMatrixAsList",getBooleanMatrixAsList)

val getByteVector = callback("getByteVector")
if(getByteVector != null)
	throw Exception("getByteVector not null!")
callback("setByteVector",getByteVector)
val getByteVectorAsList = callback("getByteVectorAsList")
if(getByteVectorAsList != null)
	throw Exception("getByteVectorAsList not null!")
callback("setByteVectorAsList",getByteVectorAsList)
val getByteMatrix = callback("getByteMatrix")
if(getByteMatrix != null)
	throw Exception("getByteMatrix not null!")
callback("setByteMatrix",getByteMatrix)
val getByteMatrixAsList = callback("getByteMatrixAsList")
if(getByteMatrixAsList != null)
	throw Exception("getByteMatrixAsList not null!")
callback("setByteMatrixAsList",getByteMatrixAsList)

val getCharacterVector = callback("getCharacterVector")
if(getCharacterVector != null)
	throw Exception("getCharacterVector not null!")
callback("setCharacterVector",getCharacterVector)
val getCharacterVectorAsList = callback("getCharacterVectorAsList")
if(getCharacterVectorAsList != null)
	throw Exception("getCharacterVectorAsList not null!")
callback("setCharacterVectorAsList",getCharacterVectorAsList)
val getCharacterMatrix = callback("getCharacterMatrix")
if(getCharacterMatrix != null)
	throw Exception("getCharacterMatrix not null!")
callback("setCharacterMatrix",getCharacterMatrix)
val getCharacterMatrixAsList = callback("getCharacterMatrixAsList")
if(getCharacterMatrixAsList != null)
	throw Exception("getCharacterMatrixAsList not null!")
callback("setCharacterMatrixAsList",getCharacterMatrixAsList)

val getDecimalVector = callback("getDecimalVector")
if(getDecimalVector != null)
	throw Exception("getDecimalVector not null!")
callback("setDecimalVector",getDecimalVector)
val getDecimalVectorAsList = callback("getDecimalVectorAsList")
if(getDecimalVectorAsList != null)
	throw Exception("getDecimalVectorAsList not null!")
callback("setDecimalVectorAsList",getDecimalVectorAsList)
val getDecimalMatrix = callback("getDecimalMatrix")
if(getDecimalMatrix != null)
	throw Exception("getDecimalMatrix not null!")
callback("setDecimalMatrix",getDecimalMatrix)
val getDecimalMatrixAsList = callback("getDecimalMatrixAsList")
if(getDecimalMatrixAsList != null)
	throw Exception("getDecimalMatrixAsList not null!")
callback("setDecimalMatrixAsList",getDecimalMatrixAsList)

val getDoubleVector = callback("getDoubleVector")
if(getDoubleVector != null)
	throw Exception("getDoubleVector not null!")
callback("setDoubleVector",getDoubleVector)
val getDoubleVectorAsList = callback("getDoubleVectorAsList")
if(getDoubleVectorAsList != null)
	throw Exception("getDoubleVectorAsList not null!")
callback("setDoubleVectorAsList",getDoubleVectorAsList)
val getDoubleMatrix = callback("getDoubleMatrix")
if(getDoubleMatrix != null)
	throw Exception("getDoubleMatrix not null!")
callback("setDoubleMatrix",getDoubleMatrix)
val getDoubleMatrixAsList = callback("getDoubleMatrixAsList")
if(getDoubleMatrixAsList != null)
	throw Exception("getDoubleMatrixAsList not null!")
callback("setDoubleMatrixAsList",getDoubleMatrixAsList)

val getFloatVector = callback("getFloatVector")
if(getFloatVector != null)
	throw Exception("getFloatVector not null!")
callback("setFloatVector",getFloatVector)
val getFloatVectorAsList = callback("getFloatVectorAsList")
if(getFloatVectorAsList != null)
	throw Exception("getFloatVectorAsList not null!")
callback("setFloatVectorAsList",getFloatVectorAsList)
val getFloatMatrix = callback("getFloatMatrix")
if(getFloatMatrix != null)
	throw Exception("getFloatMatrix not null!")
callback("setFloatMatrix",getFloatMatrix)
val getFloatMatrixAsList = callback("getFloatMatrixAsList")
if(getFloatMatrixAsList != null)
	throw Exception("getFloatMatrixAsList not null!")
callback("setFloatMatrixAsList",getFloatMatrixAsList)

val getIntegerVector = callback("getIntegerVector")
if(getIntegerVector != null)
	throw Exception("getIntegerVector not null!")
callback("setIntegerVector",getIntegerVector)
val getIntegerVectorAsList = callback("getIntegerVectorAsList")
if(getIntegerVectorAsList != null)
	throw Exception("getIntegerVectorAsList not null!")
callback("setIntegerVectorAsList",getIntegerVectorAsList)
val getIntegerMatrix = callback("getIntegerMatrix")
if(getIntegerMatrix != null)
	throw Exception("getIntegerMatrix not null!")
callback("setIntegerMatrix",getIntegerMatrix)
val getIntegerMatrixAsList = callback("getIntegerMatrixAsList")
if(getIntegerMatrixAsList != null)
	throw Exception("getIntegerMatrixAsList not null!")
callback("setIntegerMatrixAsList",getIntegerMatrixAsList)

val getLongVector = callback("getLongVector")
if(getLongVector != null)
	throw Exception("getLongVector not null!")
callback("setLongVector",getLongVector)
val getLongVectorAsList = callback("getLongVectorAsList")
if(getLongVectorAsList != null)
	throw Exception("getLongVectorAsList not null!")
callback("setLongVectorAsList",getLongVectorAsList)
val getLongMatrix = callback("getLongMatrix")
if(getLongMatrix != null)
	throw Exception("getLongMatrix not null!")
callback("setLongMatrix",getLongMatrix)
val getLongMatrixAsList = callback("getLongMatrixAsList")
if(getLongMatrixAsList != null)
	throw Exception("getLongMatrixAsList not null!")
callback("setLongMatrixAsList",getLongMatrixAsList)

val getPercentVector = callback("getPercentVector")
if(getPercentVector != null)
	throw Exception("getPercentVector not null!")
callback("setPercentVector",getPercentVector)
val getPercentVectorAsList = callback("getPercentVectorAsList")
if(getPercentVectorAsList != null)
	throw Exception("getPercentVectorAsList not null!")
callback("setPercentVectorAsList",getPercentVectorAsList)
val getPercentMatrix = callback("getPercentMatrix")
if(getPercentMatrix != null)
	throw Exception("getPercentMatrix not null!")
callback("setPercentMatrix",getPercentMatrix)
val getPercentMatrixAsList = callback("getPercentMatrixAsList")
if(getPercentMatrixAsList != null)
	throw Exception("getPercentMatrixAsList not null!")
callback("setPercentMatrixAsList",getPercentMatrixAsList)

val getShortVector = callback("getShortVector")
if(getShortVector != null)
	throw Exception("getShortVector not null!")
callback("setShortVector",getShortVector)
val getShortVectorAsList = callback("getShortVectorAsList")
if(getShortVectorAsList != null)
	throw Exception("getShortVectorAsList not null!")
callback("setShortVectorAsList",getShortVectorAsList)
val getShortMatrix = callback("getShortMatrix")
if(getShortMatrix != null)
	throw Exception("getShortMatrix not null!")
callback("setShortMatrix",getShortMatrix)
val getShortMatrixAsList = callback("getShortMatrixAsList")
if(getShortMatrixAsList != null)
	throw Exception("getShortMatrixAsList not null!")
callback("setShortMatrixAsList",getShortMatrixAsList)

val getStringVector = callback("getStringVector")
if(getStringVector != null)
	throw Exception("getStringVector not null!")
callback("setStringVector",getStringVector)
val getStringVectorAsList = callback("getStringVectorAsList")
if(getStringVectorAsList != null)
	throw Exception("getStringVectorAsList not null!")
callback("setStringVectorAsList",getStringVectorAsList)
val getStringMatrix = callback("getStringMatrix")
if(getStringMatrix != null)
	throw Exception("getStringMatrix not null!")
callback("setStringMatrix",getStringMatrix)
val getStringMatrixAsList = callback("getStringMatrixAsList")
if(getStringMatrixAsList != null)
	throw Exception("getStringMatrixAsList not null!")
callback("setStringMatrixAsList",getStringMatrixAsList)
