println("getBoolean")
if(bindings.containsKey("getBoolean"))
	throw Exception("getBoolean already defined!")
val getBoolean = callback("getBoolean")
val getBooleanType = getBoolean::class
println(getBooleanType)
println(getBoolean)
if(getBooleanType != Boolean::class)
	throw Exception("getBoolean not Boolean!")
callback("setBoolean",getBoolean)

println("getBooleanVector")
if(bindings.containsKey("getBooleanVector"))
	throw Exception("getBooleanVector already defined!")
val getBooleanVector = callback("getBooleanVector")
val getBooleanVectorType = getBooleanVector[0]::class
println(getBooleanVectorType)
println(getBooleanVector)
if(getBooleanVectorType != Boolean::class)
	throw Exception("getBooleanVector not Boolean!")
callback("setBooleanVector",getBooleanVector)

println("getBooleanVectorAsList")
if(bindings.containsKey("getBooleanVectorAsList"))
	throw Exception("getBooleanVectorAsList already defined!")
val getBooleanVectorAsList = callback("getBooleanVectorAsList")
val getBooleanVectorAsListType = getBooleanVectorAsList[0]::class
println(getBooleanVectorAsListType)
println(getBooleanVectorAsList)
if(getBooleanVectorAsListType != Boolean::class)
	throw Exception("getBooleanVectorAsList not Boolean!")
callback("setBooleanVectorAsList",getBooleanVectorAsList)

println("getBooleanMatrix")
if(bindings.containsKey("getBooleanMatrix"))
	throw Exception("getBooleanMatrix already defined!")
val getBooleanMatrix = callback("getBooleanMatrix")
val getBooleanMatrixType = getBooleanMatrix[0][0]::class
println(getBooleanMatrixType)
println(getBooleanMatrix)
if(getBooleanMatrixType != Boolean::class)
	throw Exception("getBooleanMatrix not Boolean!")
callback("setBooleanMatrix",getBooleanMatrix)

println("getBooleanMatrixAsList")
if(bindings.containsKey("getBooleanMatrixAsList"))
	throw Exception("getBooleanMatrixAsList already defined!")
val getBooleanMatrixAsList = callback("getBooleanMatrixAsList")
val getBooleanMatrixAsListType = getBooleanMatrixAsList[0][0]::class
println(getBooleanMatrixAsListType)
println(getBooleanMatrixAsList)
if(getBooleanMatrixAsListType != Boolean::class)
	throw Exception("getBooleanMatrixAsList not Boolean!")
callback("setBooleanMatrixAsList",getBooleanMatrixAsList)
