println("getString")
if(binding.containsKey("getString"))
	throw Exception("getString already defined!")
val getString: String = callback("getString")
val getStringType = getString::class
println(getStringType)
println(getString)
if(getStringType != String::class)
	throw Exception("getString not String!")
callback<Unit>("setString",getString)

println("getStringWithNull")
if(binding.containsKey("getStringWithNull"))
	throw Exception("getStringWithNull already defined!")
val getStringWithNull: String? = callback("getStringWithNull")
println(getStringWithNull)
if(getStringWithNull != null)
	throw Exception("getStringWithNull not null!")
callback<Unit>("setStringWithNull",getStringWithNull)

println("getStringVector")
if(binding.containsKey("getStringVector"))
	throw Exception("getStringVector already defined!")
val getStringVector: Array<String> = callback("getStringVector")
val getStringVectorType = getStringVector[0]!!::class
println(getStringVectorType)
println(getStringVector)
if(getStringVectorType != String::class)
	throw Exception("getStringVector not String!")
callback<Unit>("setStringVector",getStringVector)

println("getStringVectorWithNull")
if(binding.containsKey("getStringVectorWithNull"))
	throw Exception("getStringVectorWithNull already defined!")
val getStringVectorWithNull: Array<String?> = callback("getStringVectorWithNull")
val getStringVectorWithNullType = getStringVectorWithNull[0]!!::class
println(getStringVectorWithNullType)
println(getStringVectorWithNull)
if(getStringVectorWithNullType != String::class)
	throw Exception("getStringVectorWithNull not String!")
if(getStringVectorWithNull[1] != null)
	throw Exception("getStringVectorWithNull[1] not null!")
callback<Unit>("setStringVectorWithNull",getStringVectorWithNull)

println("getStringVectorAsList")
if(binding.containsKey("getStringVectorAsList"))
	throw Exception("getStringVectorAsList already defined!")
val getStringVectorAsList: Array<String> = callback("getStringVectorAsList")
val getStringVectorAsListType = getStringVectorAsList[0]!!::class
println(getStringVectorAsListType)
println(getStringVectorAsList)
if(getStringVectorAsListType != String::class)
	throw Exception("getStringVectorAsList not String!")
callback<Unit>("setStringVectorAsList",getStringVectorAsList)

println("getStringVectorAsListWithNull")
if(binding.containsKey("getStringVectorAsListWithNull"))
	throw Exception("getStringVectorAsListWithNull already defined!")
val getStringVectorAsListWithNull: Array<String?> = callback("getStringVectorAsListWithNull")
val getStringVectorAsListWithNullType = getStringVectorAsListWithNull[0]!!::class
println(getStringVectorAsListWithNullType)
println(getStringVectorAsListWithNull)
if(getStringVectorAsListWithNullType != String::class)
	throw Exception("getStringVectorAsListWithNull not String!")
if(getStringVectorAsListWithNull[1] != null)
	throw Exception("getStringVectorAsListWithNull[1] not null!")
callback<Unit>("setStringVectorAsListWithNull",getStringVectorAsListWithNull)

println("getStringMatrix")
if(binding.containsKey("getStringMatrix"))
	throw Exception("getStringMatrix already defined!")
val getStringMatrix: Array<Array<String>> = callback("getStringMatrix")
val getStringMatrixType = getStringMatrix[0][0]!!::class
println(getStringMatrixType)
println(getStringMatrix)
if(getStringMatrixType != String::class)
	throw Exception("getStringMatrix not String!")
callback<Unit>("setStringMatrix",getStringMatrix)

println("getStringMatrixWithNull")
if(binding.containsKey("getStringMatrixWithNull"))
	throw Exception("getStringMatrixWithNull already defined!")
val getStringMatrixWithNull: Array<Array<String?>> = callback("getStringMatrixWithNull")
val getStringMatrixWithNullType = getStringMatrixWithNull[0][1]!!::class
println(getStringMatrixWithNullType)
println(getStringMatrixWithNull)
if(getStringMatrixWithNullType != String::class)
	throw Exception("getStringMatrixWithNull not String!")
if(getStringMatrixWithNull[0][0] != null)
	throw Exception("getStringMatrixWithNull[0][0] not null!")
if(getStringMatrixWithNull[1][1] != null)
	throw Exception("getStringMatrixWithNull[1][1] not null!")
if(getStringMatrixWithNull[2][2] != null)
	throw Exception("getStringMatrixWithNull[2][2] not null!")
callback<Unit>("setStringMatrixWithNull",getStringMatrixWithNull)

println("getStringMatrixAsList")
if(binding.containsKey("getStringMatrixAsList"))
	throw Exception("getStringMatrixAsList already defined!")
val getStringMatrixAsList: Array<Array<String>> = callback("getStringMatrixAsList")
val getStringMatrixAsListType = getStringMatrixAsList[0][0]!!::class
println(getStringMatrixAsListType)
println(getStringMatrixAsList)
if(getStringMatrixAsListType != String::class)
	throw Exception("getStringMatrixAsList not String!")
callback<Unit>("setStringMatrixAsList",getStringMatrixAsList)

println("getStringMatrixAsListWithNull")
if(binding.containsKey("getStringMatrixAsListWithNull"))
	throw Exception("getStringMatrixAsListWithNull already defined!")
val getStringMatrixAsListWithNull: Array<Array<String?>> = callback("getStringMatrixAsListWithNull")
val getStringMatrixAsListWithNullType = getStringMatrixAsListWithNull[0][1]!!::class
println(getStringMatrixAsListWithNullType)
println(getStringMatrixAsListWithNull)
if(getStringMatrixAsListWithNullType != String::class)
	throw Exception("getStringMatrixAsListWithNull not String!")
if(getStringMatrixAsListWithNull[0][0] != null)
	throw Exception("getStringMatrixAsListWithNull[0][0] not null!")
if(getStringMatrixAsListWithNull[1][1] != null)
	throw Exception("getStringMatrixAsListWithNull[1][1] not null!")
if(getStringMatrixAsListWithNull[2][2] != null)
	throw Exception("getStringMatrixAsListWithNull[2][2] not null!")
callback<Unit>("setStringMatrixAsListWithNull",getStringMatrixAsListWithNull)
