println("getInteger")
if(binding.containsKey("getInteger"))
	throw Exception("getInteger already defined!")
val getInteger: Int = callback("getInteger")
val getIntegerType = getInteger::class
println(getIntegerType)
println(getInteger)
if(getIntegerType != Integer::class)
	throw Exception("getInteger not Integer!")
callback<Unit>("setInteger",getInteger)

println("getIntegerVector")
if(binding.containsKey("getIntegerVector"))
	throw Exception("getIntegerVector already defined!")
val getIntegerVector: IntArray = callback("getIntegerVector")
val getIntegerVectorType = getIntegerVector[0]::class
println(getIntegerVectorType)
println(getIntegerVector)
if(getIntegerVectorType != Integer::class)
	throw Exception("getIntegerVector not Integer!")
callback<Unit>("setIntegerVector",getIntegerVector)

println("getIntegerVectorAsList")
if(binding.containsKey("getIntegerVectorAsList"))
	throw Exception("getIntegerVectorAsList already defined!")
val getIntegerVectorAsList: IntArray = callback("getIntegerVectorAsList")
val getIntegerVectorAsListType = getIntegerVectorAsList[0]::class
println(getIntegerVectorAsListType)
println(getIntegerVectorAsList)
if(getIntegerVectorAsListType != Integer::class)
	throw Exception("getIntegerVectorAsList not Integer!")
callback<Unit>("setIntegerVectorAsList",getIntegerVectorAsList)

println("getIntegerMatrix")
if(binding.containsKey("getIntegerMatrix"))
	throw Exception("getIntegerMatrix already defined!")
val getIntegerMatrix: Array<IntArray> = callback("getIntegerMatrix")
val getIntegerMatrixType = getIntegerMatrix[0][0]::class
println(getIntegerMatrixType)
println(getIntegerMatrix)
if(getIntegerMatrixType != Integer::class)
	throw Exception("getIntegerMatrix not Integer!")
callback<Unit>("setIntegerMatrix",getIntegerMatrix)

println("getIntegerMatrixAsList")
if(binding.containsKey("getIntegerMatrixAsList"))
	throw Exception("getIntegerMatrixAsList already defined!")
val getIntegerMatrixAsList: Array<IntArray> = callback("getIntegerMatrixAsList")
val getIntegerMatrixAsListType = getIntegerMatrixAsList[0][0]::class
println(getIntegerMatrixAsListType)
println(getIntegerMatrixAsList)
if(getIntegerMatrixAsListType != Integer::class)
	throw Exception("getIntegerMatrixAsList not Integer!")
callback<Unit>("setIntegerMatrixAsList",getIntegerMatrixAsList)
