(defmacro defined [& var]
    `(try 
        (or 
            (boolean (resolve ~@var)) 
            (not (nil? (eval ~@var)))
        ) (catch Exception e# false)
    )
)

(println "getBoolean")
(if-not (nil? getBoolean)
	(throw (Exception. "getBoolean already defined!"))
)
(def getBoolean putBoolean)
(def getBooleanType (class getBoolean))
(println getBooleanType)
(println getBoolean)
(if-not (= getBooleanType Boolean))
	(throw (Exception. "getBoolean not boolean!"))
)

(println "getBooleanVector")
(if-not (nil? getBooleanVector)
	(throw (Exception. "getBooleanVector already defined!"))
)
(def getBooleanVector putBooleanVector)
(def getBooleanVectorType (class getBooleanVector[0]))
(println getBooleanVectorType)
(println getBooleanVector)
(if-not (= getBooleanVectorType Boolean))
	(throw (Exception. "getBooleanVector not boolean!"))
)

(println "getBooleanVectorAsList")
(if-not (nil? getBooleanVectorAsList)
	(throw (Exception. "getBooleanVectorAsList already defined!"))
)
(def getBooleanVectorAsList putBooleanVectorAsList)
(def getBooleanVectorAsListType (class getBooleanVectorAsList[0]))
(println getBooleanVectorAsListType)
(println getBooleanVectorAsList)
(if-not (= getBooleanVectorAsListType Boolean))
	(throw (Exception. "getBooleanVectorAsList not boolean!"))
)

(println "getBooleanMatrix")
(if-not (nil? getBooleanMatrix)
	(throw (Exception. "getBooleanMatrix already defined!"))
)
(def getBooleanMatrix putBooleanMatrix)
(def getBooleanMatrixType (class getBooleanMatrix[0][0]))
(println getBooleanMatrixType)
(println getBooleanMatrix)
(if-not (= getBooleanMatrixType Boolean))
	(throw (Exception. "getBooleanMatrix not boolean!"))
)

(println "getBooleanMatrixAsList")
(if-not (nil? getBooleanMatrixAsList)
	(throw (Exception. "getBooleanMatrixAsList already defined!"))
)
(def getBooleanMatrixAsList putBooleanMatrixAsList)
(def getBooleanMatrixAsListType (class getBooleanMatrixAsList[0][0]))
(println getBooleanMatrixAsListType)
(println getBooleanMatrixAsList)
(if-not (= getBooleanMatrixAsListType Boolean))
	(throw (Exception. "getBooleanMatrixAsList not boolean!"))
)
