(defmacro defined [& var]
    `(try 
        (or 
            (boolean (resolve ~@var)) 
            (not (nil? (eval ~@var)))
        ) (catch Exception e# false)
    )
)

(println "getPercent")
(if (defined 'getPercent)
	(throw (Exception. "getPercent already defined!"))
)
(def getPercent putPercent)
(def getPercentType (class getPercent))
(println getPercentType)
(println getPercent)
(if-not (= getPercentType Float)
	(throw (Exception. "getPercent not Float!"))
)

(println "getPercentVector")
(if (defined 'getPercentVector)
	(throw (Exception. "getPercentVector already defined!"))
)
(def getPercentVector putPercentVector)
(def getPercentVectorType (class getPercentVector[0]))
(println getPercentVectorType)
(println getPercentVector)
(if-not (= getPercentVectorType Float)
	(throw (Exception. "getPercentVector not Float!"))
)

(println "getPercentVectorAsList")
(if (defined 'getPercentVectorAsList)
	(throw (Exception. "getPercentVectorAsList already defined!"))
)
(def getPercentVectorAsList putPercentVectorAsList)
(def getPercentVectorAsListType (class getPercentVectorAsList[0]))
(println getPercentVectorAsListType)
(println getPercentVectorAsList)
(if-not (= getPercentVectorAsListType Float)
	(throw (Exception. "getPercentVectorAsList not Float!"))
)

(println "getPercentMatrix")
(if (defined 'getPercentMatrix)
	(throw (Exception. "getPercentMatrix already defined!"))
)
(def getPercentMatrix putPercentMatrix)
(def getPercentMatrixType (class getPercentMatrix[0][0]))
(println getPercentMatrixType)
(println getPercentMatrix)
(if-not (= getPercentMatrixType Float)
	(throw (Exception. "getPercentMatrix not Float!"))
)

(println "getPercentMatrixAsList")
(if (defined 'getPercentMatrixAsList)
	(throw (Exception. "getPercentMatrixAsList already defined!"))
)
(def getPercentMatrixAsList putPercentMatrixAsList)
(def getPercentMatrixAsListType (class getPercentMatrixAsList[0][0]))
(println getPercentMatrixAsListType)
(println getPercentMatrixAsList)
(if-not (= getPercentMatrixAsListType Float)
	(throw (Exception. "getPercentMatrixAsList not Float!"))
)
