(println "getDouble")
(if-not (nil? getDouble)
	(throw (Exception. "getDouble already defined!"))
)
(def getDouble putDouble)
(def getDoubleType getDouble.class)
(println getDoubleType)
(println getDouble)
(if-not (= getDoubleType Float)
	(throw (Exception. "getDouble not Float!"))
)

(println "getDoubleVector")
(if-not (nil? getDoubleVector)
	(throw (Exception. "getDoubleVector already defined!"))
)
(def getDoubleVector putDoubleVector)
(def getDoubleVectorType getDoubleVector[0].class)
(println getDoubleVectorType)
(println getDoubleVector)
(if-not (= getDoubleVectorType Float)
	(throw (Exception. "getDoubleVector not Float!"))
)

(println "getDoubleVectorAsList")
(if-not (nil? getDoubleVectorAsList)
	(throw (Exception. "getDoubleVectorAsList already defined!"))
)
(def getDoubleVectorAsList putDoubleVectorAsList)
(def getDoubleVectorAsListType getDoubleVectorAsList[0].class)
(println getDoubleVectorAsListType)
(println getDoubleVectorAsList)
(if-not (= getDoubleVectorAsListType Float)
	(throw (Exception. "getDoubleVectorAsList not Float!"))
)

(println "getDoubleMatrix")
(if-not (nil? getDoubleMatrix)
	(throw (Exception. "getDoubleMatrix already defined!"))
)
(def getDoubleMatrix putDoubleMatrix)
(def getDoubleMatrixType getDoubleMatrix[0][0].class)
(println getDoubleMatrixType)
(println getDoubleMatrix)
(if-not (= getDoubleMatrixType Float)
	(throw (Exception. "getDoubleMatrix not Float!"))
)

(println "getDoubleMatrixAsList")
(if-not (nil? getDoubleMatrixAsList)
	(throw (Exception. "getDoubleMatrixAsList already defined!"))
)
(def getDoubleMatrixAsList putDoubleMatrixAsList)
(def getDoubleMatrixAsListType getDoubleMatrixAsList[0][0].class)
(println getDoubleMatrixAsListType)
(println getDoubleMatrixAsList)
(if-not (= getDoubleMatrixAsListType Float)
	(throw (Exception. "getDoubleMatrixAsList not Float!"))
)
