(println "getShort")
(if-not (nil? getShort)
	(throw (Exception. "getShort already defined!"))
)
(def getShort putShort)
(def getShortType getShort.class)
(println getShortType)
(println getShort)
(if-not (= getShortType Integer))
	(throw (Exception. "getShort not Integer!"))
)

(println "getShortVector")
(if-not (nil? getShortVector)
	(throw (Exception. "getShortVector already defined!"))
)
(def getShortVector putShortVector)
(def getShortVectorType getShortVector[0].class)
(println getShortVectorType)
(println getShortVector)
(if-not (= getShortVectorType Integer))
	(throw (Exception. "getShortVector not Integer!"))
)

(println "getShortVectorAsList")
(if-not (nil? getShortVectorAsList)
	(throw (Exception. "getShortVectorAsList already defined!"))
)
(def getShortVectorAsList putShortVectorAsList)
(def getShortVectorAsListType getShortVectorAsList[0].class)
(println getShortVectorAsListType)
(println getShortVectorAsList)
(if-not (= getShortVectorAsListType Integer))
	(throw (Exception. "getShortVectorAsList not Integer!"))
)

(println "getShortMatrix")
(if-not (nil? getShortMatrix)
	(throw (Exception. "getShortMatrix already defined!"))
)
(def getShortMatrix putShortMatrix)
(def getShortMatrixType getShortMatrix[0][0].class)
(println getShortMatrixType)
(println getShortMatrix)
(if-not (= getShortMatrixType Integer))
	(throw (Exception. "getShortMatrix not Integer!"))
)

(println "getShortMatrixAsList")
(if-not (nil? getShortMatrixAsList)
	(throw (Exception. "getShortMatrixAsList already defined!"))
)
(def getShortMatrixAsList putShortMatrixAsList)
(def getShortMatrixAsListType getShortMatrixAsList[0][0].class)
(println getShortMatrixAsListType)
(println getShortMatrixAsList)
(if-not (= getShortMatrixAsListType Integer))
	(throw (Exception. "getShortMatrixAsList not Integer!"))
)
