(println "getFloat")
(if-not (nil? getFloat)
	(throw (Exception. "getFloat already defined!"))
)
(def getFloat putFloat)
(def getFloatType getFloat.class)
(println getFloatType)
(println getFloat)
(if-not (= getFloatType Float)
	(throw (Exception. "getFloat not Float!"))
)

(println "getFloatVector")
(if-not (nil? getFloatVector)
	(throw (Exception. "getFloatVector already defined!"))
)
(def getFloatVector putFloatVector)
(def getFloatVectorType getFloatVector[0].class)
(println getFloatVectorType)
(println getFloatVector)
(if-not (= getFloatVectorType Float)
	(throw (Exception. "getFloatVector not Float!"))
)

(println "getFloatVectorAsList")
(if-not (nil? getFloatVectorAsList)
	(throw (Exception. "getFloatVectorAsList already defined!"))
)
(def getFloatVectorAsList putFloatVectorAsList)
(def getFloatVectorAsListType getFloatVectorAsList[0].class)
(println getFloatVectorAsListType)
(println getFloatVectorAsList)
(if-not (= getFloatVectorAsListType Float)
	(throw (Exception. "getFloatVectorAsList not Float!"))
)

(println "getFloatMatrix")
(if-not (nil? getFloatMatrix)
	(throw (Exception. "getFloatMatrix already defined!"))
)
(def getFloatMatrix putFloatMatrix)
(def getFloatMatrixType getFloatMatrix[0][0].class)
(println getFloatMatrixType)
(println getFloatMatrix)
(if-not (= getFloatMatrixType Float)
	(throw (Exception. "getFloatMatrix not Float!"))
)

(println "getFloatMatrixAsList")
(if-not (nil? getFloatMatrixAsList)
	(throw (Exception. "getFloatMatrixAsList already defined!"))
)
(def getFloatMatrixAsList putFloatMatrixAsList)
(def getFloatMatrixAsListType getFloatMatrixAsList[0][0].class)
(println getFloatMatrixAsListType)
(println getFloatMatrixAsList)
(if-not (= getFloatMatrixAsListType Float)
	(throw (Exception. "getFloatMatrixAsList not Float!"))
)
