(defmacro defined [& var]
    `(try 
        (or 
            (boolean (resolve ~@var)) 
            (not (nil? (eval ~@var)))
        ) (catch Exception e# false)
    )
)

(println "getCharacter")
(if (defined 'getCharacter)
	(throw (Exception. "getCharacter already defined!"))
)
(def getCharacter putCharacter)
(def getCharacterType (class getCharacter))
(println getCharacterType)
(println getCharacter)
(if-not (= getCharacterType Integer)
	(throw (Exception. "getCharacter not Integer"))
)

(println "getCharacterVector")
(if (defined 'getCharacterVector)
	(throw (Exception. "getCharacterVector already defined!"))
)
(def getCharacterVector putCharacterVector)
(def getCharacterVectorType (class getCharacterVector[0]))
(println getCharacterVectorType)
(println getCharacterVector)
(if-not (= getCharacterVectorType Integer)
	(throw (Exception. "getCharacterVector not Integer"))
)

(println "getCharacterVectorAsList")
(if (defined 'getCharacterVectorAsList)
	(throw (Exception. "getCharacterVectorAsList already defined!"))
)
(def getCharacterVectorAsList putCharacterVectorAsList)
(def getCharacterVectorAsListType (class getCharacterVectorAsList[0]))
(println getCharacterVectorAsListType)
(println getCharacterVectorAsList)
(if-not (= getCharacterVectorAsListType Integer)
	(throw (Exception. "getCharacterVectorAsList not Integer"))
)

(println "getCharacterMatrix")
(if (defined 'getCharacterMatrix)
	(throw (Exception. "getCharacterMatrix already defined!"))
)
(def getCharacterMatrix putCharacterMatrix)
(def getCharacterMatrixType (class getCharacterMatrix[0][0]))
(println getCharacterMatrixType)
(println getCharacterMatrix)
(if-not (= getCharacterMatrixType Integer)
	(throw (Exception. "getCharacterMatrix not Integer"))
)

(println "getCharacterMatrixAsList")
(if (defined 'getCharacterMatrixAsList)
	(throw (Exception. "getCharacterMatrixAsList already defined!"))
)
(def getCharacterMatrixAsList putCharacterMatrixAsList)
(def getCharacterMatrixAsListType (class getCharacterMatrixAsList[0][0]))
(println getCharacterMatrixAsListType)
(println getCharacterMatrixAsList)
(if-not (= getCharacterMatrixAsListType Integer)
	(throw (Exception. "getCharacterMatrixAsList not Integer"))
)