(defmacro defined [& var]
    `(try 
        (or 
            (boolean (resolve ~@var)) 
            (not (nil? (eval ~@var)))
        ) (catch Exception e# false)
    )
)

(println "getDecimal")
(if (defined 'getDecimal)
	(throw (Exception. "getDecimal already defined!"))
)
(def getDecimal putDecimal)
(def getDecimalType (class getDecimal))
(println getDecimalType)
(println getDecimal)
(if-not (= getDecimalType Float)
	(throw (Exception. "getDecimal not Float!"))
)

(println "getDecimalVector")
(if (defined 'getDecimalVector)
	(throw (Exception. "getDecimalVector already defined!"))
)
(def getDecimalVector putDecimalVector)
(def getDecimalVectorType (class getDecimalVector[0]))
(println getDecimalVectorType)
(println getDecimalVector)
(if-not (= getDecimalVectorType Float)
	(throw (Exception. "getDecimalVector not Float!"))
)

(println "getDecimalVectorAsList")
(if (defined 'getDecimalVectorAsList)
	(throw (Exception. "getDecimalVectorAsList already defined!"))
)
(def getDecimalVectorAsList putDecimalVectorAsList)
(def getDecimalVectorAsListType (class getDecimalVectorAsList[0]))
(println getDecimalVectorAsListType)
(println getDecimalVectorAsList)
(if-not (= getDecimalVectorAsListType Float)
	(throw (Exception. "getDecimalVectorAsList not Float!"))
)

(println "getDecimalMatrix")
(if (defined 'getDecimalMatrix)
	(throw (Exception. "getDecimalMatrix already defined!"))
)
(def getDecimalMatrix putDecimalMatrix)
(def getDecimalMatrixType (class getDecimalMatrix[0][0]))
(println getDecimalMatrixType)
(println getDecimalMatrix)
(if-not (= getDecimalMatrixType Float)
	(throw (Exception. "getDecimalMatrix not Float!"))
)

(println "getDecimalMatrixAsList")
(if (defined 'getDecimalMatrixAsList)
	(throw (Exception. "getDecimalMatrixAsList already defined!"))
)
(def getDecimalMatrixAsList putDecimalMatrixAsList)
(def getDecimalMatrixAsListType (class getDecimalMatrixAsList[0][0]))
(println getDecimalMatrixAsListType)
(println getDecimalMatrixAsList)
(if-not (= getDecimalMatrixAsListType Float)
	(throw (Exception. "getDecimalMatrixAsList not Float!"))
)
