(println "getDecimal")
(if-not (nil? getDecimal)
	(throw (Exception. "getDecimal already defined!"))
)
(def getDecimal putDecimal)
(def getDecimalType getDecimal.class)
(println getDecimalType)
(println getDecimal)
(if-not (= getDecimalType Float)
	(throw (Exception. "getDecimal not Float!"))
)

(println "getDecimalVector")
(if-not (nil? getDecimalVector)
	(throw (Exception. "getDecimalVector already defined!"))
)
(def getDecimalVector putDecimalVector)
(def getDecimalVectorType getDecimalVector[0].class)
(println getDecimalVectorType)
(println getDecimalVector)
(if-not (= getDecimalVectorType Float)
	(throw (Exception. "getDecimalVector not Float!"))
)

(println "getDecimalVectorAsList")
(if-not (nil? getDecimalVectorAsList)
	(throw (Exception. "getDecimalVectorAsList already defined!"))
)
(def getDecimalVectorAsList putDecimalVectorAsList)
(def getDecimalVectorAsListType getDecimalVectorAsList[0].class)
(println getDecimalVectorAsListType)
(println getDecimalVectorAsList)
(if-not (= getDecimalVectorAsListType Float)
	(throw (Exception. "getDecimalVectorAsList not Float!"))
)

(println "getDecimalMatrix")
(if-not (nil? getDecimalMatrix)
	(throw (Exception. "getDecimalMatrix already defined!"))
)
(def getDecimalMatrix putDecimalMatrix)
(def getDecimalMatrixType getDecimalMatrix[0][0].class)
(println getDecimalMatrixType)
(println getDecimalMatrix)
(if-not (= getDecimalMatrixType Float)
	(throw (Exception. "getDecimalMatrix not Float!"))
)

(println "getDecimalMatrixAsList")
(if-not (nil? getDecimalMatrixAsList)
	(throw (Exception. "getDecimalMatrixAsList already defined!"))
)
(def getDecimalMatrixAsList putDecimalMatrixAsList)
(def getDecimalMatrixAsListType getDecimalMatrixAsList[0][0].class)
(println getDecimalMatrixAsListType)
(println getDecimalMatrixAsList)
(if-not (= getDecimalMatrixAsListType Float)
	(throw (Exception. "getDecimalMatrixAsList not Float!"))
)
