(println "getString")
(if-not (nil? getString)
	(throw (Exception. "getString already defined!"))
)
(def getString putString)
(def getStringType getString.class)
(println getStringType)
(println getString)
(if-not (= getStringType String)
	(throw (Exception. "getString not String!"))
)

(println "getStringWithNull")
(if-not (nil? getStringWithNull)
	(throw (Exception. "getStringWithNull already defined!"))
)
(def getStringWithNull putStringWithNull)
(def getStringWithNullType getStringWithNull.class)
(println getStringWithNullType)
(println getStringWithNull)
(if-not (nil? getStringWithNull)
	(throw (Exception. "getStringWithNull not null!"))
)

(println "getStringVector")
(if-not (nil? getStringVector)
	(throw (Exception. "getStringVector already defined!"))
)
(def getStringVector putStringVector)
(def getStringVectorType getStringVector[0].class)
(println getStringVectorType)
(println getStringVector)
(if-not (= getStringVectorType String)
	(throw (Exception. "getStringVector not String!"))
)

(println "getStringVectorWithNull")
(if-not (nil? getStringVectorWithNull)
	(throw (Exception. "getStringVectorWithNull already defined!"))
)
(def getStringVectorWithNull putStringVectorWithNull)
(def getStringVectorWithNullType getStringVectorWithNull[0].class)
(println getStringVectorWithNullType)
(println getStringVectorWithNull)
(if-not (= getStringVectorWithNullType String)
	(throw (Exception. "getStringVectorWithNull not String!"))
)
(if-not (nil? getStringVectorWithNull[1])
	(throw (Exception. "getStringVectorWithNull[1] not null!"))
)

(println "getStringVectorAsList")
(if-not (nil? getStringVectorAsList)
	(throw (Exception. "getStringVectorAsList already defined!"))
)
(def getStringVectorAsList putStringVectorAsList)
(def getStringVectorAsListType getStringVectorAsList[0].class)
(println getStringVectorAsListType)
(println getStringVectorAsList)
(if-not (= getStringVectorAsListType String)
	(throw (Exception. "getStringVectorAsList not String!"))
)

(println "getStringVectorAsListWithNull")
(if-not (nil? getStringVectorAsListWithNull)
	(throw (Exception. "getStringVectorAsListWithNull already defined!"))
)
(def getStringVectorAsListWithNull putStringVectorAsListWithNull)
(def getStringVectorAsListWithNullType getStringVectorAsListWithNull[0].class)
(println getStringVectorAsListWithNullType)
(println getStringVectorAsListWithNull)
(if-not (= getStringVectorAsListWithNullType String)
	(throw (Exception. "getStringVectorAsListWithNull not String!"))
)
(if-not (nil? getStringVectorAsListWithNull[1])
	(throw (Exception. "getStringVectorAsListWithNull[1] not null!"))
)

(println "getStringMatrix")
(if-not (nil? getStringMatrix)
	(throw (Exception. "getStringMatrix already defined!"))
)
(def getStringMatrix putStringMatrix)
(def getStringMatrixType getStringMatrix[0][0].class)
(println getStringMatrixType)
(println getStringMatrix)
(if-not (= getStringMatrixType String)
	(throw (Exception. "getStringMatrix not String!"))
)

(println "getStringMatrixWithNull")
(if-not (nil? getStringMatrixWithNull)
	(throw (Exception. "getStringMatrixWithNull already defined!"))
)
(def getStringMatrixWithNull putStringMatrixWithNull)
(def getStringMatrixWithNullType getStringMatrixWithNull[0][1].class)
(println getStringMatrixWithNullType)
(println getStringMatrixWithNull)
(if-not (= getStringMatrixWithNullType String)
	(throw (Exception. "getStringMatrixWithNull not String!"))
)
(if-not (nil? getStringMatrixWithNull[0][0])
	(throw (Exception. "getStringMatrixWithNull[0][0] not null!"))
)
(if-not (nil? getStringMatrixWithNull[1][1])
	(throw (Exception. "getStringMatrixWithNull[1][1] not null!"))
)
(if-not (nil? getStringMatrixWithNull[2][2])
	(throw (Exception. "getStringMatrixWithNull[2][2] not null!"))
)

(println "getStringMatrixAsList")
(if-not (nil? getStringMatrixAsList)
	(throw (Exception. "getStringMatrixAsList already defined!"))
)
(def getStringMatrixAsList putStringMatrixAsList)
(def getStringMatrixAsListType getStringMatrixAsList[0][0].class)
(println getStringMatrixAsListType)
(println getStringMatrixAsList)
(if-not (= getStringMatrixAsListType String)
	(throw (Exception. "getStringMatrixAsList not String!"))
)

(println "getStringMatrixAsListWithNull")
(if-not (nil? getStringMatrixAsListWithNull)
	(throw (Exception. "getStringMatrixAsListWithNull already defined!"))
)
(def getStringMatrixAsListWithNull putStringMatrixAsListWithNull)
(def getStringMatrixAsListWithNullType getStringMatrixAsListWithNull[0][1].class)
(println getStringMatrixAsListWithNullType)
(println getStringMatrixAsListWithNull)
(if-not (= getStringMatrixAsListWithNullType String)
	(throw (Exception. "getStringMatrixAsListWithNull not String!"))
)
(if-not (nil? getStringMatrixAsListWithNull[0][0])
	(throw (Exception. "getStringMatrixAsListWithNull[0][0] not null!"))
)
(if-not (nil? getStringMatrixAsListWithNull[1][1])
	(throw (Exception. "getStringMatrixAsListWithNull[1][1] not null!"))
)
(if-not (nil? getStringMatrixAsListWithNull[2][2])
	(throw (Exception. "getStringMatrixAsListWithNull[2][2] not null!"))
)
