(println "getCharacter")
(if-not (nil? getCharacter)
	(throw (Exception. "getCharacter already defined!"))
)
(def getCharacter putCharacter)
(def getCharacterType getCharacter.class)
(println getCharacterType)
(println getCharacter)
(if-not (= getCharacterType Integer)
	(throw (Exception. "getCharacter not Integer"))
)

(println "getCharacterVector")
(if-not (nil? getCharacterVector)
	(throw (Exception. "getCharacterVector already defined!"))
)
(def getCharacterVector putCharacterVector)
(def getCharacterVectorType getCharacterVector[0].class)
(println getCharacterVectorType)
(println getCharacterVector)
(if-not (= getCharacterVectorType Integer)
	(throw (Exception. "getCharacterVector not Integer"))
)

(println "getCharacterVectorAsList")
(if-not (nil? getCharacterVectorAsList)
	(throw (Exception. "getCharacterVectorAsList already defined!"))
)
(def getCharacterVectorAsList putCharacterVectorAsList)
(def getCharacterVectorAsListType getCharacterVectorAsList[0].class)
(println getCharacterVectorAsListType)
(println getCharacterVectorAsList)
(if-not (= getCharacterVectorAsListType Integer)
	(throw (Exception. "getCharacterVectorAsList not Integer"))
)

(println "getCharacterMatrix")
(if-not (nil? getCharacterMatrix)
	(throw (Exception. "getCharacterMatrix already defined!"))
)
(def getCharacterMatrix putCharacterMatrix)
(def getCharacterMatrixType getCharacterMatrix[0][0].class)
(println getCharacterMatrixType)
(println getCharacterMatrix)
(if-not (= getCharacterMatrixType Integer)
	(throw (Exception. "getCharacterMatrix not Integer"))
)

(println "getCharacterMatrixAsList")
(if-not (nil? getCharacterMatrixAsList)
	(throw (Exception. "getCharacterMatrixAsList already defined!"))
)
(def getCharacterMatrixAsList putCharacterMatrixAsList)
(def getCharacterMatrixAsListType getCharacterMatrixAsList[0][0].class)
(println getCharacterMatrixAsListType)
(println getCharacterMatrixAsList)
(if-not (= getCharacterMatrixAsListType Integer)
	(throw (Exception. "getCharacterMatrixAsList not Integer"))
)