(defmacro defined [& var]
    `(try 
        (or 
            (boolean (resolve ~@var)) 
            (not (nil? (eval ~@var)))
        ) (catch Exception e# false)
    )
)

(println "getByte")
(if (defined 'getByte)
	(throw (Exception. "getByte already defined"))
)
(def getByte putByte)
(def getByteType (class getByte))
(println getByteType)
(println getByte)
(if-not (= getByteType Integer)
	(throw (Exception. "getByte not Integer!"))
)

(println "getByteVector")
(if (defined 'getByteVector)
	(throw (Exception. "getByteVector already defined"))
)
(def getByteVector putByteVector)
(def getByteVectorType (class getByteVector[0]))
(println getByteVectorType)
(println getByteVector)
(if-not (= getByteVectorType Integer)
	(throw (Exception. "getByteVector not Integer!"))
)

(println "getByteVectorAsList")
(if (defined 'getByteVectorAsList)
	(throw (Exception. "getByteVectorAsList already defined"))
)
(def getByteVectorAsList putByteVectorAsList)
(def getByteVectorAsListType (class getByteVectorAsList[0]))
(println getByteVectorAsListType)
(println getByteVectorAsList)
(if-not (= getByteVectorAsListType Integer)
	(throw (Exception. "getByteVectorAsList not Integer!"))
)

(println "getByteMatrix")
(if (defined 'getByteMatrix)
	(throw (Exception. "getByteMatrix already defined"))
)
(def getByteMatrix putByteMatrix)
(def getByteMatrixType (class getByteMatrix[0][0]))
(println getByteMatrixType)
(println getByteMatrix)
(if-not (= getByteMatrixType Integer)
	(throw (Exception. "getByteMatrix not Integer!"))
)

(println "getByteMatrixAsList")
(if (defined 'getByteMatrixAsList)
	(throw (Exception. "getByteMatrixAsList already defined"))
)
(def getByteMatrixAsList putByteMatrixAsList)
(def getByteMatrixAsListType (class getByteMatrixAsList[0][0]))
(println getByteMatrixAsListType)
(println getByteMatrixAsList)
(if-not (= getByteMatrixAsListType Integer)
	(throw (Exception. "getByteMatrixAsList not Integer!"))
)
