(println "getInteger")
(if-not (nil? getInteger)
	(throw (Exception. "getInteger already defined!"))
)
(def getInteger putInteger)
(def getIntegerType getInteger.class)
(println getIntegerType)
(println getInteger)
(if-not (= getIntegerType Integer)
	(throw (Exception. "getInteger not Integer!"))
)

(println "getIntegerVector")
(if-not (nil? getIntegerVector)
	(throw (Exception. "getIntegerVector already defined!"))
)
(def getIntegerVector putIntegerVector)
(def getIntegerVectorType getIntegerVector[0].class)
(println getIntegerVectorType)
(println getIntegerVector)
(if-not (= getIntegerVectorType Integer)
	(throw (Exception. "getIntegerVector not Integer!"))
)

(println "getIntegerVectorAsList")
(if-not (nil? getIntegerVectorAsList)
	(throw (Exception. "getIntegerVectorAsList already defined!"))
)
(def getIntegerVectorAsList putIntegerVectorAsList)
(def getIntegerVectorAsListType getIntegerVectorAsList[0].class)
(println getIntegerVectorAsListType)
(println getIntegerVectorAsList)
(if-not (= getIntegerVectorAsListType Integer)
	(throw (Exception. "getIntegerVectorAsList not Integer!"))
)

(println "getIntegerMatrix")
(if-not (nil? getIntegerMatrix)
	(throw (Exception. "getIntegerMatrix already defined!"))
)
(def getIntegerMatrix putIntegerMatrix)
(def getIntegerMatrixType getIntegerMatrix[0][0].class)
(println getIntegerMatrixType)
(println getIntegerMatrix)
(if-not (= getIntegerMatrixType Integer)
	(throw (Exception. "getIntegerMatrix not Integer!"))
)

(println "getIntegerMatrixAsList")
(if-not (nil? getIntegerMatrixAsList)
	(throw (Exception. "getIntegerMatrixAsList already defined!"))
)
(def getIntegerMatrixAsList putIntegerMatrixAsList)
(def getIntegerMatrixAsListType getIntegerMatrixAsList[0][0].class)
(println getIntegerMatrixAsListType)
(println getIntegerMatrixAsList)
(if-not (= getIntegerMatrixAsListType Integer)
	(throw (Exception. "getIntegerMatrixAsList not Integer!"))
)
