(defmacro defined [& var]
    `(try 
        (or 
            (boolean (resolve ~@var)) 
            (not (nil? (eval ~@var)))
        ) (catch Exception e# false)
    )
)

(println "getShort")
(if (defined 'getShort)
	(throw (Exception. "getShort already defined!"))
)
(def getShort putShort)
(def getShortType (class getShort))
(println getShortType)
(println getShort)
(if-not (= getShortType Integer))
	(throw (Exception. "getShort not Integer!"))
)

(println "getShortVector")
(if (defined 'getShortVector)
	(throw (Exception. "getShortVector already defined!"))
)
(def getShortVector putShortVector)
(def getShortVectorType (class getShortVector[0]))
(println getShortVectorType)
(println getShortVector)
(if-not (= getShortVectorType Integer))
	(throw (Exception. "getShortVector not Integer!"))
)

(println "getShortVectorAsList")
(if (defined 'getShortVectorAsList)
	(throw (Exception. "getShortVectorAsList already defined!"))
)
(def getShortVectorAsList putShortVectorAsList)
(def getShortVectorAsListType (class getShortVectorAsList[0]))
(println getShortVectorAsListType)
(println getShortVectorAsList)
(if-not (= getShortVectorAsListType Integer))
	(throw (Exception. "getShortVectorAsList not Integer!"))
)

(println "getShortMatrix")
(if (defined 'getShortMatrix)
	(throw (Exception. "getShortMatrix already defined!"))
)
(def getShortMatrix putShortMatrix)
(def getShortMatrixType (class getShortMatrix[0][0]))
(println getShortMatrixType)
(println getShortMatrix)
(if-not (= getShortMatrixType Integer))
	(throw (Exception. "getShortMatrix not Integer!"))
)

(println "getShortMatrixAsList")
(if (defined 'getShortMatrixAsList)
	(throw (Exception. "getShortMatrixAsList already defined!"))
)
(def getShortMatrixAsList putShortMatrixAsList)
(def getShortMatrixAsListType (class getShortMatrixAsList[0][0]))
(println getShortMatrixAsListType)
(println getShortMatrixAsList)
(if-not (= getShortMatrixAsListType Integer))
	(throw (Exception. "getShortMatrixAsList not Integer!"))
)
