(println "getPercent")
(if-not (nil? getPercent)
	(throw (Exception. "getPercent already defined!"))
)
(def getPercent putPercent)
(def getPercentType getPercent.class)
(println getPercentType)
(println getPercent)
(if-not (= getPercentType Float)
	(throw (Exception. "getPercent not Float!"))
)

(println "getPercentVector")
(if-not (nil? getPercentVector)
	(throw (Exception. "getPercentVector already defined!"))
)
(def getPercentVector putPercentVector)
(def getPercentVectorType getPercentVector[0].class)
(println getPercentVectorType)
(println getPercentVector)
(if-not (= getPercentVectorType Float)
	(throw (Exception. "getPercentVector not Float!"))
)

(println "getPercentVectorAsList")
(if-not (nil? getPercentVectorAsList)
	(throw (Exception. "getPercentVectorAsList already defined!"))
)
(def getPercentVectorAsList putPercentVectorAsList)
(def getPercentVectorAsListType getPercentVectorAsList[0].class)
(println getPercentVectorAsListType)
(println getPercentVectorAsList)
(if-not (= getPercentVectorAsListType Float)
	(throw (Exception. "getPercentVectorAsList not Float!"))
)

(println "getPercentMatrix")
(if-not (nil? getPercentMatrix)
	(throw (Exception. "getPercentMatrix already defined!"))
)
(def getPercentMatrix putPercentMatrix)
(def getPercentMatrixType getPercentMatrix[0][0].class)
(println getPercentMatrixType)
(println getPercentMatrix)
(if-not (= getPercentMatrixType Float)
	(throw (Exception. "getPercentMatrix not Float!"))
)

(println "getPercentMatrixAsList")
(if-not (nil? getPercentMatrixAsList)
	(throw (Exception. "getPercentMatrixAsList already defined!"))
)
(def getPercentMatrixAsList putPercentMatrixAsList)
(def getPercentMatrixAsListType getPercentMatrixAsList[0][0].class)
(println getPercentMatrixAsListType)
(println getPercentMatrixAsList)
(if-not (= getPercentMatrixAsListType Float)
	(throw (Exception. "getPercentMatrixAsList not Float!"))
)
