(println "getLong")
(if-not (nil? getLong)
	(throw (Exception. "getLong already defined!"))
)
(def getLong putLong)
(def getLongType getLong.class)
(println getLongType)
(println getLong)
(if-not (= getLongType Integer)
	(throw (Exception. "getLong not Integer!"))
)

(println "getLongVector")
(if-not (nil? getLongVector)
	(throw (Exception. "getLongVector already defined!"))
)
(def getLongVector putLongVector)
(def getLongVectorType getLongVector[0].class)
(println getLongVectorType)
(println getLongVector)
(if-not (= getLongVectorType Integer)
	(throw (Exception. "getLongVector not Integer!"))
)

(println "getLongVectorAsList")
(if-not (nil? getLongVectorAsList)
	(throw (Exception. "getLongVectorAsList already defined!"))
)
(def getLongVectorAsList putLongVectorAsList)
(def getLongVectorAsListType getLongVectorAsList[0].class)
(println getLongVectorAsListType)
(println getLongVectorAsList)
(if-not (= getLongVectorAsListType Integer)
	(throw (Exception. "getLongVectorAsList not Integer!"))
)

(println "getLongMatrix")
(if-not (nil? getLongMatrix)
	(throw (Exception. "getLongMatrix already defined!"))
)
(def getLongMatrix putLongMatrix)
(def getLongMatrixType getLongMatrix[0][0].class)
(println getLongMatrixType)
(println getLongMatrix)
(if-not (= getLongMatrixType Integer)
	(throw (Exception. "getLongMatrix not Integer!"))
)

(println "getLongMatrixAsList")
(if-not (nil? getLongMatrixAsList)
	(throw (Exception. "getLongMatrixAsList already defined!"))
)
(def getLongMatrixAsList putLongMatrixAsList)
(def getLongMatrixAsListType getLongMatrixAsList[0][0].class)
(println getLongMatrixAsListType)
(println getLongMatrixAsList)
(if-not (= getLongMatrixAsListType Integer)
	(throw (Exception. "getLongMatrixAsList not Integer!"))
)
