(println "getByte")
(if-not (nil? getByte)
	(throw (Exception. "getByte already defined"))
)
(def getByte putByte)
(def getByteType getByte.class)
(println getByteType)
(println getByte)
(if-not (= getByteType Integer)
	(throw (Exception. "getByte not Integer!"))
)

(println "getByteVector")
(if-not (nil? getByteVector)
	(throw (Exception. "getByteVector already defined"))
)
(def getByteVector putByteVector)
(def getByteVectorType getByteVector[0].class)
(println getByteVectorType)
(println getByteVector)
(if-not (= getByteVectorType Integer)
	(throw (Exception. "getByteVector not Integer!"))
)

(println "getByteVectorAsList")
(if-not (nil? getByteVectorAsList)
	(throw (Exception. "getByteVectorAsList already defined"))
)
(def getByteVectorAsList putByteVectorAsList)
(def getByteVectorAsListType getByteVectorAsList[0].class)
(println getByteVectorAsListType)
(println getByteVectorAsList)
(if-not (= getByteVectorAsListType Integer)
	(throw (Exception. "getByteVectorAsList not Integer!"))
)

(println "getByteMatrix")
(if-not (nil? getByteMatrix)
	(throw (Exception. "getByteMatrix already defined"))
)
(def getByteMatrix putByteMatrix)
(def getByteMatrixType getByteMatrix[0][0].class)
(println getByteMatrixType)
(println getByteMatrix)
(if-not (= getByteMatrixType Integer)
	(throw (Exception. "getByteMatrix not Integer!"))
)

(println "getByteMatrixAsList")
(if-not (nil? getByteMatrixAsList)
	(throw (Exception. "getByteMatrixAsList already defined"))
)
(def getByteMatrixAsList putByteMatrixAsList)
(def getByteMatrixAsListType getByteMatrixAsList[0][0].class)
(println getByteMatrixAsListType)
(println getByteMatrixAsList)
(if-not (= getByteMatrixAsListType Integer)
	(throw (Exception. "getByteMatrixAsList not Integer!"))
)
