println("getDouble")
if(binding.hasVariable('getDouble'))
	throw new Exception("getDouble already defined!")
getDouble = callback("getDouble")
getDoubleType = getDouble.getClass()
println(getDoubleType)
println(getDouble)
if(getDoubleType != Double.class)
	throw new Exception("getDouble not Double!")
callback("setDouble",getDouble)

println("getDoubleVector")
if(binding.hasVariable('getDoubleVector'))
	throw new Exception("getDoubleVector already defined!")
getDoubleVector = callback("getDoubleVector")
getDoubleVectorType = getDoubleVector[0].getClass()
println(getDoubleVectorType)
println(getDoubleVector)
if(getDoubleVectorType != Double.class)
	throw new Exception("getDoubleVector not Double!")
callback("setDoubleVector",getDoubleVector)

println("getDoubleVectorAsList")
if(binding.hasVariable('getDoubleVectorAsList'))
	throw new Exception("getDoubleVectorAsList already defined!")
getDoubleVectorAsList = callback("getDoubleVectorAsList")
getDoubleVectorAsListType = getDoubleVectorAsList[0].getClass()
println(getDoubleVectorAsListType)
println(getDoubleVectorAsList)
if(getDoubleVectorAsListType != Double.class)
	throw new Exception("getDoubleVectorAsList not Double!")
callback("setDoubleVectorAsList",getDoubleVectorAsList)

println("getDoubleMatrix")
if(binding.hasVariable('getDoubleMatrix'))
	throw new Exception("getDoubleMatrix already defined!")
getDoubleMatrix = callback("getDoubleMatrix")
getDoubleMatrixType = getDoubleMatrix[0][0].getClass()
println(getDoubleMatrixType)
println(getDoubleMatrix)
if(getDoubleMatrixType != Double.class)
	throw new Exception("getDoubleMatrix not Double!")
callback("setDoubleMatrix",new Object[]{getDoubleMatrix})

println("getDoubleMatrixAsList")
if(binding.hasVariable('getDoubleMatrixAsList'))
	throw new Exception("getDoubleMatrixAsList already defined!")
getDoubleMatrixAsList = callback("getDoubleMatrixAsList")
getDoubleMatrixAsListType = getDoubleMatrixAsList[0][0].getClass()
println(getDoubleMatrixAsListType)
println(getDoubleMatrixAsList)
if(getDoubleMatrixAsListType != Double.class)
	throw new Exception("getDoubleMatrixAsList not Double!")
callback("setDoubleMatrixAsList",new Object[]{getDoubleMatrixAsList})
