println("getString")
if(binding.hasVariable('getString'))
	throw new Exception("getString already defined!")
getString = callback("getString")
getStringType = getString.getClass()
println(getStringType)
println(getString)
if(getStringType != String.class)
	throw new Exception("getString not String!")
callback("setString",getString)

println("getStringWithNull")
if(binding.hasVariable('getStringWithNull'))
	throw new Exception("getStringWithNull already defined!")
getStringWithNull = callback("getStringWithNull")
getStringWithNullType = getStringWithNull.getClass()
println(getStringWithNullType)
println(getStringWithNull)
if(getStringWithNull != null)
	throw new Exception("getStringWithNull not null!")
callback("setStringWithNull",getStringWithNull)

println("getStringVector")
if(binding.hasVariable('getStringVector'))
	throw new Exception("getStringVector already defined!")
getStringVector = callback("getStringVector")
getStringVectorType = getStringVector[0].getClass()
println(getStringVectorType)
println(getStringVector)
if(getStringVectorType != String.class)
	throw new Exception("getStringVector not String!")
callback("setStringVector",new Object[]{getStringVector})

println("getStringVectorWithNull")
if(binding.hasVariable('getStringVectorWithNull'))
	throw new Exception("getStringVectorWithNull already defined!")
getStringVectorWithNull = callback("getStringVectorWithNull")
getStringVectorWithNullType = getStringVectorWithNull[0].getClass()
println(getStringVectorWithNullType)
println(getStringVectorWithNull)
if(getStringVectorWithNullType != String.class)
	throw new Exception("getStringVectorWithNull not String!")
if(getStringVectorWithNull[1] != null)
	throw new Exception("getStringVectorWithNull[1] not null!")
callback("setStringVectorWithNull",new Object[]{getStringVectorWithNull})

println("getStringVectorAsList")
if(binding.hasVariable('getStringVectorAsList'))
	throw new Exception("getStringVectorAsList already defined!")
getStringVectorAsList = callback("getStringVectorAsList")
getStringVectorAsListType = getStringVectorAsList[0].getClass()
println(getStringVectorAsListType)
println(getStringVectorAsList)
if(getStringVectorAsListType != String.class)
	throw new Exception("getStringVectorAsList not String!")
callback("setStringVectorAsList",new Object[]{getStringVectorAsList})

println("getStringVectorAsListWithNull")
if(binding.hasVariable('getStringVectorAsListWithNull'))
	throw new Exception("getStringVectorAsListWithNull already defined!")
getStringVectorAsListWithNull = callback("getStringVectorAsListWithNull")
getStringVectorAsListWithNullType = getStringVectorAsListWithNull[0].getClass()
println(getStringVectorAsListWithNullType)
println(getStringVectorAsListWithNull)
if(getStringVectorAsListWithNullType != String.class)
	throw new Exception("getStringVectorAsListWithNull not String!")
if(getStringVectorAsListWithNull[1] != null)
	throw new Exception("getStringVectorAsListWithNull[1] not null!")
callback("setStringVectorAsListWithNull",new Object[]{getStringVectorAsListWithNull})

println("getStringMatrix")
if(binding.hasVariable('getStringMatrix'))
	throw new Exception("getStringMatrix already defined!")
getStringMatrix = callback("getStringMatrix")
getStringMatrixType = getStringMatrix[0][0].getClass()
println(getStringMatrixType)
println(getStringMatrix)
if(getStringMatrixType != String.class)
	throw new Exception("getStringMatrix not String!")
callback("setStringMatrix",new Object[]{getStringMatrix})

println("getStringMatrixWithNull")
if(binding.hasVariable('getStringMatrixWithNull'))
	throw new Exception("getStringMatrixWithNull already defined!")
getStringMatrixWithNull = callback("getStringMatrixWithNull")
getStringMatrixWithNullType = getStringMatrixWithNull[0][1].getClass()
println(getStringMatrixWithNullType)
println(getStringMatrixWithNull)
if(getStringMatrixWithNullType != String.class)
	throw new Exception("getStringMatrixWithNull not String!")
if(getStringMatrixWithNull[0][0] != null)
	throw new Exception("getStringMatrixWithNull[0][0] not null!")
if(getStringMatrixWithNull[1][1] != null)
	throw new Exception("getStringMatrixWithNull[1][1] not null!")
if(getStringMatrixWithNull[2][2] != null)
	throw new Exception("getStringMatrixWithNull[2][2] not null!")
callback("setStringMatrixWithNull",new Object[]{getStringMatrixWithNull})

println("getStringMatrixAsList")
if(binding.hasVariable('getStringMatrixAsList'))
	throw new Exception("getStringMatrixAsList already defined!")
getStringMatrixAsList = callback("getStringMatrixAsList")
getStringMatrixAsListType = getStringMatrixAsList[0][0].getClass()
println(getStringMatrixAsListType)
println(getStringMatrixAsList)
if(getStringMatrixAsListType != String.class)
	throw new Exception("getStringMatrixAsList not String!")
callback("setStringMatrixAsList",new Object[]{getStringMatrixAsList})

println("getStringMatrixAsListWithNull")
if(binding.hasVariable('getStringMatrixAsListWithNull'))
	throw new Exception("getStringMatrixAsListWithNull already defined!")
getStringMatrixAsListWithNull = callback("getStringMatrixAsListWithNull")
getStringMatrixAsListWithNullType = getStringMatrixAsListWithNull[0][1].getClass()
println(getStringMatrixAsListWithNullType)
println(getStringMatrixAsListWithNull)
if(getStringMatrixAsListWithNullType != String.class)
	throw new Exception("getStringMatrixAsListWithNull not String!")
if(getStringMatrixAsListWithNull[0][0] != null)
	throw new Exception("getStringMatrixAsListWithNull[0][0] not null!")
if(getStringMatrixAsListWithNull[1][1] != null)
	throw new Exception("getStringMatrixAsListWithNull[1][1] not null!")
if(getStringMatrixAsListWithNull[2][2] != null)
	throw new Exception("getStringMatrixAsListWithNull[2][2] not null!")
callback("setStringMatrixAsListWithNull",new Object[]{getStringMatrixAsListWithNull})
