println("getDouble")
if(binding.hasVariable('getDouble'))
	throw new Exception("getDouble already defined!")
getDouble = callback("getDouble")
getDoubleType = getDouble.getClass()
println(getDoubleType)
println(getDouble)
if(getDoubleType != Double.class)
	throw new Exception("getDouble not Double!")
if(!Double.isNaN(getDouble))
	throw new Exception("getDouble not NaN!")
callback("setDouble",getDouble)

println("getDoubleVector")
if(binding.hasVariable('getDoubleVector'))
	throw new Exception("getDoubleVector already defined!")
getDoubleVector = callback("getDoubleVector")
getDoubleVectorType = getDoubleVector[0].getClass()
println(getDoubleVectorType)
println(getDoubleVector)
if(getDoubleVectorType != Double.class)
	throw new Exception("getDoubleVector not Double!")
if(!Double.isNaN(getDoubleVector[1]))
	throw new Exception("getDoubleVector[1] not NaN!")
callback("setDoubleVector",getDoubleVector)

println("getDoubleVectorAsList")
if(binding.hasVariable('getDoubleVectorAsList'))
	throw new Exception("getDoubleVectorAsList already defined!")
getDoubleVectorAsList = callback("getDoubleVectorAsList")
getDoubleVectorAsListType = getDoubleVectorAsList[0].getClass()
println(getDoubleVectorAsListType)
println(getDoubleVectorAsList)
if(getDoubleVectorAsListType != Double.class)
	throw new Exception("getDoubleVectorAsList not Double!")
if(!Double.isNaN(getDoubleVectorAsList[1]))
	throw new Exception("getDoubleVectorAsList[1] not NaN!")
callback("setDoubleVectorAsList",getDoubleVectorAsList)

println("getDoubleMatrix")
if(binding.hasVariable('getDoubleMatrix'))
	throw new Exception("getDoubleMatrix already defined!")
getDoubleMatrix = callback("getDoubleMatrix")
getDoubleMatrixType = getDoubleMatrix[0][0].getClass()
println(getDoubleMatrixType)
println(getDoubleMatrix)
if(getDoubleMatrixType != Double.class)
	throw new Exception("getDoubleMatrix not Double!")
if(!Double.isNaN(getDoubleMatrix[0][0]))
	throw new Exception("getDoubleMatrix[0][0] not NaN!")
if(!Double.isNaN(getDoubleMatrix[1][1]))
	throw new Exception("getDoubleMatrix[1][1] not NaN!")
if(!Double.isNaN(getDoubleMatrix[2][2]))
	throw new Exception("getDoubleMatrix[2][2] not NaN!")
callback("setDoubleMatrix",new Object[]{getDoubleMatrix})

println("getDoubleMatrixAsList")
if(binding.hasVariable('getDoubleMatrixAsList'))
	throw new Exception("getDoubleMatrixAsList already defined!")
getDoubleMatrixAsList = callback("getDoubleMatrixAsList")
getDoubleMatrixAsListType = getDoubleMatrixAsList[0][0].getClass()
println(getDoubleMatrixAsListType)
println(getDoubleMatrixAsList)
if(getDoubleMatrixAsListType != Double.class)
	throw new Exception("getDoubleMatrixAsList not Double!")
if(!Double.isNaN(getDoubleMatrixAsList[0][0]))
	throw new Exception("getDoubleMatrixAsList[0][0] not NaN!")
if(!Double.isNaN(getDoubleMatrixAsList[1][1]))
	throw new Exception("getDoubleMatrixAsList[1][1] not NaN!")
if(!Double.isNaN(getDoubleMatrixAsList[2][2]))
	throw new Exception("getDoubleMatrixAsList[2][2] not NaN!")
callback("setDoubleMatrixAsList",new Object[]{getDoubleMatrixAsList})
