println("getDecimal")
if(binding.hasVariable('getDecimal'))
	throw new Exception("getDecimal already defined!")
getDecimal = callback("getDecimal")
getDecimalType = getDecimal.getClass()
println(getDecimalType)
println(getDecimal)
if(getDecimalType != Double.class)
	throw new Exception("getDecimal not Double!")
callback("setDecimal",getDecimal)

println("getDecimalVector")
if(binding.hasVariable('getDecimalVector'))
	throw new Exception("getDecimalVector already defined!")
getDecimalVector = callback("getDecimalVector")
getDecimalVectorType = getDecimalVector[0].getClass()
println(getDecimalVectorType)
println(getDecimalVector)
if(getDecimalVectorType != Double.class)
	throw new Exception("getDecimalVector not Double!")
callback("setDecimalVector",getDecimalVector)

println("getDecimalVectorAsList")
if(binding.hasVariable('getDecimalVectorAsList'))
	throw new Exception("getDecimalVectorAsList already defined!")
getDecimalVectorAsList = callback("getDecimalVectorAsList")
getDecimalVectorAsListType = getDecimalVectorAsList[0].getClass()
println(getDecimalVectorAsListType)
println(getDecimalVectorAsList)
if(getDecimalVectorAsListType != Double.class)
	throw new Exception("getDecimalVectorAsList not Double!")
callback("setDecimalVectorAsList",getDecimalVectorAsList)

println("getDecimalMatrix")
if(binding.hasVariable('getDecimalMatrix'))
	throw new Exception("getDecimalMatrix already defined!")
getDecimalMatrix = callback("getDecimalMatrix")
getDecimalMatrixType = getDecimalMatrix[0][0].getClass()
println(getDecimalMatrixType)
println(getDecimalMatrix)
if(getDecimalMatrixType != Double.class)
	throw new Exception("getDecimalMatrix not Double!")
callback("setDecimalMatrix",new Object[]{getDecimalMatrix})

println("getDecimalMatrixAsList")
if(binding.hasVariable('getDecimalMatrixAsList'))
	throw new Exception("getDecimalMatrixAsList already defined!")
getDecimalMatrixAsList = callback("getDecimalMatrixAsList")
getDecimalMatrixAsListType = getDecimalMatrixAsList[0][0].getClass()
println(getDecimalMatrixAsListType)
println(getDecimalMatrixAsList)
if(getDecimalMatrixAsListType != Double.class)
	throw new Exception("getDecimalMatrixAsList not Double!")
callback("setDecimalMatrixAsList",new Object[]{getDecimalMatrixAsList})
