println("getCharacter")
if(binding.hasVariable('getCharacter'))
	throw new Exception("getCharacter already defined!")
getCharacter = callback("getCharacter")
getCharacterType = getCharacter.getClass()
println(getCharacterType)
println(getCharacter)
if(getCharacterType != Character.class)
	throw new Exception("getCharacter not Character!")
callback("setCharacter",getCharacter)

println("getCharacterVector")
if(binding.hasVariable('getCharacterVector'))
	throw new Exception("getCharacterVector already defined!")
getCharacterVector = callback("getCharacterVector")
getCharacterVectorType = getCharacterVector[0].getClass()
println(getCharacterVectorType)
println(getCharacterVector)
if(getCharacterVectorType != Character.class)
	throw new Exception("getCharacterVector not Character!")
callback("setCharacterVector",getCharacterVector)

println("getCharacterVectorAsList")
if(binding.hasVariable('getCharacterVectorAsList'))
	throw new Exception("getCharacterVectorAsList already defined!")
getCharacterVectorAsList = callback("getCharacterVectorAsList")
getCharacterVectorAsListType = getCharacterVectorAsList[0].getClass()
println(getCharacterVectorAsListType)
println(getCharacterVectorAsList)
if(getCharacterVectorAsListType != Character.class)
	throw new Exception("getCharacterVectorAsList not Character!")
callback("setCharacterVectorAsList",getCharacterVectorAsList)

println("getCharacterMatrix")
if(binding.hasVariable('getCharacterMatrix'))
	throw new Exception("getCharacterMatrix already defined!")
getCharacterMatrix = callback("getCharacterMatrix")
getCharacterMatrixType = getCharacterMatrix[0][0].getClass()
println(getCharacterMatrixType)
println(getCharacterMatrix)
if(getCharacterMatrixType != Character.class)
	throw new Exception("getCharacterMatrix not Character!")
callback("setCharacterMatrix",new Object[]{getCharacterMatrix})

println("getCharacterMatrixAsList")
if(binding.hasVariable('getCharacterMatrixAsList'))
	throw new Exception("getCharacterMatrixAsList already defined!")
getCharacterMatrixAsList = callback("getCharacterMatrixAsList")
getCharacterMatrixAsListType = getCharacterMatrixAsList[0][0].getClass()
println(getCharacterMatrixAsListType)
println(getCharacterMatrixAsList)
if(getCharacterMatrixAsListType != Character.class)
	throw new Exception("getCharacterMatrixAsList not Character!")
callback("setCharacterMatrixAsList",new Object[]{getCharacterMatrixAsList})
	