println("getInteger")
if(binding.hasVariable('getInteger'))
	throw new Exception("getInteger already defined!")
getInteger = callback("getInteger")
getIntegerType = getInteger.getClass()
println(getIntegerType)
println(getInteger)
if(getIntegerType != Integer.class)
	throw new Exception("getInteger not Integer!")
callback("setInteger",getInteger)

println("getIntegerVector")
if(binding.hasVariable('getIntegerVector'))
	throw new Exception("getIntegerVector already defined!")
getIntegerVector = callback("getIntegerVector")
getIntegerVectorType = getIntegerVector[0].getClass()
println(getIntegerVectorType)
println(getIntegerVector)
if(getIntegerVectorType != Integer.class)
	throw new Exception("getIntegerVector not Integer!")
callback("setIntegerVector",getIntegerVector)

println("getIntegerVectorAsList")
if(binding.hasVariable('getIntegerVectorAsList'))
	throw new Exception("getIntegerVectorAsList already defined!")
getIntegerVectorAsList = callback("getIntegerVectorAsList")
getIntegerVectorAsListType = getIntegerVectorAsList[0].getClass()
println(getIntegerVectorAsListType)
println(getIntegerVectorAsList)
if(getIntegerVectorAsListType != Integer.class)
	throw new Exception("getIntegerVectorAsList not Integer!")
callback("setIntegerVectorAsList",getIntegerVectorAsList)

println("getIntegerMatrix")
if(binding.hasVariable('getIntegerMatrix'))
	throw new Exception("getIntegerMatrix already defined!")
getIntegerMatrix = callback("getIntegerMatrix")
getIntegerMatrixType = getIntegerMatrix[0][0].getClass()
println(getIntegerMatrixType)
println(getIntegerMatrix)
if(getIntegerMatrixType != Integer.class)
	throw new Exception("getIntegerMatrix not Integer!")
callback("setIntegerMatrix",new Object[]{getIntegerMatrix})

println("getIntegerMatrixAsList")
if(binding.hasVariable('getIntegerMatrixAsList'))
	throw new Exception("getIntegerMatrixAsList already defined!")
getIntegerMatrixAsList = callback("getIntegerMatrixAsList")
getIntegerMatrixAsListType = getIntegerMatrixAsList[0][0].getClass()
println(getIntegerMatrixAsListType)
println(getIntegerMatrixAsList)
if(getIntegerMatrixAsListType != Integer.class)
	throw new Exception("getIntegerMatrixAsList not Integer!")
callback("setIntegerMatrixAsList",new Object[]{getIntegerMatrixAsList})
