println("getLong")
if(binding.hasVariable('getLong'))
	throw new Exception("getLong already defined!")
getLong = callback("getLong")
getLongType = getLong.getClass()
println(getLongType)
println(getLong)
if(getLongType != Long.class)
	throw new Exception("getLong not Long!")
callback("setLong",getLong)

println("getLongVector")
if(binding.hasVariable('getLongVector'))
	throw new Exception("getLongVector already defined!")
getLongVector = callback("getLongVector")
getLongVectorType = getLongVector[0].getClass()
println(getLongVectorType)
println(getLongVector)
if(getLongVectorType != Long.class)
	throw new Exception("getLongVector not Long!")
callback("setLongVector",getLongVector)

println("getLongVectorAsList")
if(binding.hasVariable('getLongVectorAsList'))
	throw new Exception("getLongVectorAsList already defined!")
getLongVectorAsList = callback("getLongVectorAsList")
getLongVectorAsListType = getLongVectorAsList[0].getClass()
println(getLongVectorAsListType)
println(getLongVectorAsList)
if(getLongVectorAsListType != Long.class)
	throw new Exception("getLongVectorAsList not Long!")
callback("setLongVectorAsList",getLongVectorAsList)

println("getLongMatrix")
if(binding.hasVariable('getLongMatrix'))
	throw new Exception("getLongMatrix already defined!")
getLongMatrix = callback("getLongMatrix")
getLongMatrixType = getLongMatrix[0][0].getClass()
println(getLongMatrixType)
println(getLongMatrix)
if(getLongMatrixType != Long.class)
	throw new Exception("getLongMatrix not Long!")
callback("setLongMatrix",new Object[]{getLongMatrix})

println("getLongMatrixAsList")
if(binding.hasVariable('getLongMatrixAsList'))
	throw new Exception("getLongMatrixAsList already defined!")
getLongMatrixAsList = callback("getLongMatrixAsList")
getLongMatrixAsListType = getLongMatrixAsList[0][0].getClass()
println(getLongMatrixAsListType)
println(getLongMatrixAsList)
if(getLongMatrixAsListType != Long.class)
	throw new Exception("getLongMatrixAsList not Long!")
callback("setLongMatrixAsList",new Object[]{getLongMatrixAsList})
