println("getPercent")
if(binding.hasVariable('getPercent'))
	throw new Exception("getPercent already defined!")
getPercent = callback("getPercent")
getPercentType = getPercent.getClass()
println(getPercentType)
println(getPercent)
if(getPercentType != Double.class)
	throw new Exception("getPercent not Double!")
callback("setPercent",getPercent)

println("getPercentVector")
if(binding.hasVariable('getPercentVector'))
	throw new Exception("getPercentVector already defined!")
getPercentVector = callback("getPercentVector")
getPercentVectorType = getPercentVector[0].getClass()
println(getPercentVectorType)
println(getPercentVector)
if(getPercentVectorType != Double.class)
	throw new Exception("getPercentVector not Double!")
callback("setPercentVector",getPercentVector)

println("getPercentVectorAsList")
if(binding.hasVariable('getPercentVectorAsList'))
	throw new Exception("getPercentVectorAsList already defined!")
getPercentVectorAsList = callback("getPercentVectorAsList")
getPercentVectorAsListType = getPercentVectorAsList[0].getClass()
println(getPercentVectorAsListType)
println(getPercentVectorAsList)
if(getPercentVectorAsListType != Double.class)
	throw new Exception("getPercentVectorAsList not Double!")
callback("setPercentVectorAsList",getPercentVectorAsList)

println("getPercentMatrix")
if(binding.hasVariable('getPercentMatrix'))
	throw new Exception("getPercentMatrix already defined!")
getPercentMatrix = callback("getPercentMatrix")
getPercentMatrixType = getPercentMatrix[0][0].getClass()
println(getPercentMatrixType)
println(getPercentMatrix)
if(getPercentMatrixType != Double.class)
	throw new Exception("getPercentMatrix not Double!")
callback("setPercentMatrix",new Object[]{getPercentMatrix})

println("getPercentMatrixAsList")
if(binding.hasVariable('getPercentMatrixAsList'))
	throw new Exception("getPercentMatrixAsList already defined!")
getPercentMatrixAsList = callback("getPercentMatrixAsList")
getPercentMatrixAsListType = getPercentMatrixAsList[0][0].getClass()
println(getPercentMatrixAsListType)
println(getPercentMatrixAsList)
if(getPercentMatrixAsListType != Double.class)
	throw new Exception("getPercentMatrixAsList not Double!")
callback("setPercentMatrixAsList",new Object[]{getPercentMatrixAsList})
