println("getShort")
if(binding.hasVariable('getShort'))
	throw new Exception("getShort already defined!")
getShort = callback("getShort")
getShortType = getShort.getClass()
println(getShortType)
println(getShort)
if(getShortType != Short.class)
	throw new Exception("getShort not Short!")
callback("setShort",getShort)

println("getShortVector")
if(binding.hasVariable('getShortVector'))
	throw new Exception("getShortVector already defined!")
getShortVector = callback("getShortVector")
getShortVectorType = getShortVector[0].getClass()
println(getShortVectorType)
println(getShortVector)
if(getShortVectorType != Short.class)
	throw new Exception("getShortVector not Short!")
callback("setShortVector",getShortVector)

println("getShortVectorAsList")
if(binding.hasVariable('getShortVectorAsList'))
	throw new Exception("getShortVectorAsList already defined!")
getShortVectorAsList = callback("getShortVectorAsList")
getShortVectorAsListType = getShortVectorAsList[0].getClass()
println(getShortVectorAsListType)
println(getShortVectorAsList)
if(getShortVectorAsListType != Short.class)
	throw new Exception("getShortVectorAsList not Short!")
callback("setShortVectorAsList",getShortVectorAsList)

println("getShortMatrix")
if(binding.hasVariable('getShortMatrix'))
	throw new Exception("getShortMatrix already defined!")
getShortMatrix = callback("getShortMatrix")
getShortMatrixType = getShortMatrix[0][0].getClass()
println(getShortMatrixType)
println(getShortMatrix)
if(getShortMatrixType != Short.class)
	throw new Exception("getShortMatrix not Short!")
callback("setShortMatrix",new Object[]{getShortMatrix})

println("getShortMatrixAsList")
if(binding.hasVariable('getShortMatrixAsList'))
	throw new Exception("getShortMatrixAsList already defined!")
getShortMatrixAsList = callback("getShortMatrixAsList")
getShortMatrixAsListType = getShortMatrixAsList[0][0].getClass()
println(getShortMatrixAsListType)
println(getShortMatrixAsList)
if(getShortMatrixAsListType != Short.class)
	throw new Exception("getShortMatrixAsList not Short!")
callback("setShortMatrixAsList",new Object[]{getShortMatrixAsList})
