(def getBooleanVector putBooleanVector)
(if-not (nil? getBooleanVector)
	(throw (Exception. "getBooleanVector not null!"))
)
(def getBooleanVectorAsList putBooleanVectorAsList)
(if-not (nil? getBooleanVectorAsList)
	(throw (Exception. "getBooleanVectorAsList not null!"))
)
(def getBooleanMatrix putBooleanMatrix)
(if-not (nil? getBooleanMatrix)
	(throw (Exception. "getBooleanMatrix not null!"))
)
(def getBooleanMatrixAsList putBooleanMatrixAsList)
(if-not (nil? getBooleanMatrixAsList)
	(throw (Exception. "getBooleanMatrixAsList not null!"))
)

(def getByteVector putByteVector)
(if-not (nil? getByteVector)
	(throw (Exception. "getByteVector not null!"))
)
(def getByteVectorAsList putByteVectorAsList)
(if-not (nil? getByteVectorAsList)
	(throw (Exception. "getByteVectorAsList not null!"))
)
(def getByteMatrix putByteMatrix)
(if-not (nil? getByteMatrix)
	(throw (Exception. "getByteMatrix not null!"))
)
(def getByteMatrixAsList putByteMatrixAsList)
(if-not (nil? getByteMatrixAsList)
	(throw (Exception. "getByteMatrixAsList not null!"))
)

(def getCharacterVector putCharacterVector)
(if-not (nil? getCharacterVector)
	(throw (Exception. "getCharacterVector not null!"))
)
(def getCharacterVectorAsList putCharacterVectorAsList)
(if-not (nil? getCharacterVectorAsList)
	(throw (Exception. "getCharacterVectorAsList not null!"))
)
(def getCharacterMatrix putCharacterMatrix)
(if-not (nil? getCharacterMatrix)
	(throw (Exception. "getCharacterMatrix not null!"))
)
(def getCharacterMatrixAsList putCharacterMatrixAsList)
(if-not (nil? getCharacterMatrixAsList)
	(throw (Exception. "getCharacterMatrixAsList not null!"))
)

(def getDecimalVector putDecimalVector)
(if-not (nil? getDecimalVector)
	(throw (Exception. "getDecimalVector not null!"))
)
(def getDecimalVectorAsList putDecimalVectorAsList)
(if-not (nil? getDecimalVectorAsList)
	(throw (Exception. "getDecimalVectorAsList not null!"))
)
(def getDecimalMatrix putDecimalMatrix)
(if-not (nil? getDecimalMatrix)
	(throw (Exception. "getDecimalMatrix not null!"))
)
(def getDecimalMatrixAsList putDecimalMatrixAsList)
(if-not (nil? getDecimalMatrixAsList)
	(throw (Exception. "getDecimalMatrixAsList not null!"))
)

(def getDoubleVector putDoubleVector)
(if-not (nil? getDoubleVector)
	(throw (Exception. "getDoubleVector not null!"))
)
(def getDoubleVectorAsList putDoubleVectorAsList)
(if-not (nil? getDoubleVectorAsList)
	(throw (Exception. "getDoubleVectorAsList not null!"))
)
(def getDoubleMatrix putDoubleMatrix)
(if-not (nil? getDoubleMatrix)
	(throw (Exception. "getDoubleMatrix not null!"))
)
(def getDoubleMatrixAsList putDoubleMatrixAsList)
(if-not (nil? getDoubleMatrixAsList)
	(throw (Exception. "getDoubleMatrixAsList not null!"))
)

(def getFloatVector putFloatVector)
(if-not (nil? getFloatVector)
	(throw (Exception. "getFloatVector not null!"))
)
(def getFloatVectorAsList putFloatVectorAsList)
(if-not (nil? getFloatVectorAsList)
	(throw (Exception. "getFloatVectorAsList not null!"))
)
(def getFloatMatrix putFloatMatrix)
(if-not (nil? getFloatMatrix)
	(throw (Exception. "getFloatMatrix not null!"))
)
(def getFloatMatrixAsList putFloatMatrixAsList)
(if-not (nil? getFloatMatrixAsList)
	(throw (Exception. "getFloatMatrixAsList not null!"))
)

(def getIntegerVector putIntegerVector)
(if-not (nil? getIntegerVector)
	(throw (Exception. "getIntegerVector not null!"))
)
(def getIntegerVectorAsList putIntegerVectorAsList)
(if-not (nil? getIntegerVectorAsList)
	(throw (Exception. "getIntegerVectorAsList not null!"))
)
(def getIntegerMatrix putIntegerMatrix)
(if-not (nil? getIntegerMatrix)
	(throw (Exception. "getIntegerMatrix not null!"))
)
(def getIntegerMatrixAsList putIntegerMatrixAsList)
(if-not (nil? getIntegerMatrixAsList)
	(throw (Exception. "getIntegerMatrixAsList not null!"))
)

(def getLongVector putLongVector)
(if-not (nil? getLongVector)
	(throw (Exception. "getLongVector not null!"))
)
(def getLongVectorAsList putLongVectorAsList)
(if-not (nil? getLongVectorAsList)
	(throw (Exception. "getLongVectorAsList not null!"))
)
(def getLongMatrix putLongMatrix)
(if-not (nil? getLongMatrix)
	(throw (Exception. "getLongMatrix not null!"))
)
(def getLongMatrixAsList putLongMatrixAsList)
(if-not (nil? getLongMatrixAsList)
	(throw (Exception. "getLongMatrixAsList not null!"))
)

(def getPercentVector putPercentVector)
(if-not (nil? getPercentVector)
	(throw (Exception. "getPercentVector not null!"))
)
(def getPercentVectorAsList putPercentVectorAsList)
(if-not (nil? getPercentVectorAsList)
	(throw (Exception. "getPercentVectorAsList not null!"))
)
(def getPercentMatrix putPercentMatrix)
(if-not (nil? getPercentMatrix)
	(throw (Exception. "getPercentMatrix not null!"))
)
(def getPercentMatrixAsList putPercentMatrixAsList)
(if-not (nil? getPercentMatrixAsList)
	(throw (Exception. "getPercentMatrixAsList not null!"))
)

(def getShortVector putShortVector)
(if-not (nil? getShortVector)
	(throw (Exception. "getShortVector not null!"))
)
(def getShortVectorAsList putShortVectorAsList)
(if-not (nil? getShortVectorAsList)
	(throw (Exception. "getShortVectorAsList not null!"))
)
(def getShortMatrix putShortMatrix)
(if-not (nil? getShortMatrix)
	(throw (Exception. "getShortMatrix not null!"))
)
(def getShortMatrixAsList putShortMatrixAsList)
(if-not (nil? getShortMatrixAsList)
	(throw (Exception. "getShortMatrixAsList not null!"))
)

(def getStringVector putStringVector)
(if-not (nil? getStringVector)
	(throw (Exception. "getStringVector not null!"))
)
(def getStringVectorAsList putStringVectorAsList)
(if-not (nil? getStringVectorAsList)
	(throw (Exception. "getStringVectorAsList not null!"))
)
(def getStringMatrix putStringMatrix)
(if-not (nil? getStringMatrix)
	(throw (Exception. "getStringMatrix not null!"))
)
(def getStringMatrixAsList putStringMatrixAsList)
(if-not (nil? getStringMatrixAsList)
	(throw (Exception. "getStringMatrixAsList not null!"))
)
