(def getBooleanVector (callback "getBooleanVector"))
(if-not (nil? getBooleanVector)
	(throw (Exception. "getBooleanVector not null!"))
)
(callback "set" get)
(def getBooleanVectorAsList (callback "getBooleanVectorAsList"))
(if-not (nil? getBooleanVectorAsList)
	(throw (Exception. "getBooleanVectorAsList not null!"))
)
(callback "set" get)
(def getBooleanMatrix (callback "getBooleanMatrix"))
(if-not (nil? getBooleanMatrix)
	(throw (Exception. "getBooleanMatrix not null!"))
)
(callback "set" get)
(def getBooleanMatrixAsList (callback "getBooleanMatrixAsList"))
(if-not (nil? getBooleanMatrixAsList)
	(throw (Exception. "getBooleanMatrixAsList not null!"))
)
(callback "set" get)

(def getByteVector (callback "getByteVector"))
(if-not (nil? getByteVector)
	(throw (Exception. "getByteVector not null!"))
)
(callback "set" get)
(def getByteVectorAsList (callback "getByteVectorAsList"))
(if-not (nil? getByteVectorAsList)
	(throw (Exception. "getByteVectorAsList not null!"))
)
(callback "set" get)
(def getByteMatrix (callback "getByteMatrix"))
(if-not (nil? getByteMatrix)
	(throw (Exception. "getByteMatrix not null!"))
)
(callback "set" get)
(def getByteMatrixAsList (callback "getByteMatrixAsList"))
(if-not (nil? getByteMatrixAsList)
	(throw (Exception. "getByteMatrixAsList not null!"))
)
(callback "set" get)

(def getCharacterVector (callback "getCharacterVector"))
(if-not (nil? getCharacterVector)
	(throw (Exception. "getCharacterVector not null!"))
)
(callback "set" get)
(def getCharacterVectorAsList (callback "getCharacterVectorAsList"))
(if-not (nil? getCharacterVectorAsList)
	(throw (Exception. "getCharacterVectorAsList not null!"))
)
(callback "set" get)
(def getCharacterMatrix (callback "getCharacterMatrix"))
(if-not (nil? getCharacterMatrix)
	(throw (Exception. "getCharacterMatrix not null!"))
)
(callback "set" get)
(def getCharacterMatrixAsList (callback "getCharacterMatrixAsList"))
(if-not (nil? getCharacterMatrixAsList)
	(throw (Exception. "getCharacterMatrixAsList not null!"))
)
(callback "set" get)

(def getDecimalVector (callback "getDecimalVector"))
(if-not (nil? getDecimalVector)
	(throw (Exception. "getDecimalVector not null!"))
)
(callback "set" get)
(def getDecimalVectorAsList (callback "getDecimalVectorAsList"))
(if-not (nil? getDecimalVectorAsList)
	(throw (Exception. "getDecimalVectorAsList not null!"))
)
(callback "set" get)
(def getDecimalMatrix (callback "getDecimalMatrix"))
(if-not (nil? getDecimalMatrix)
	(throw (Exception. "getDecimalMatrix not null!"))
)
(callback "set" get)
(def getDecimalMatrixAsList (callback "getDecimalMatrixAsList"))
(if-not (nil? getDecimalMatrixAsList)
	(throw (Exception. "getDecimalMatrixAsList not null!"))
)
(callback "set" get)

(def getDoubleVector (callback "getDoubleVector"))
(if-not (nil? getDoubleVector)
	(throw (Exception. "getDoubleVector not null!"))
)
(callback "set" get)
(def getDoubleVectorAsList (callback "getDoubleVectorAsList"))
(if-not (nil? getDoubleVectorAsList)
	(throw (Exception. "getDoubleVectorAsList not null!"))
)
(callback "set" get)
(def getDoubleMatrix (callback "getDoubleMatrix"))
(if-not (nil? getDoubleMatrix)
	(throw (Exception. "getDoubleMatrix not null!"))
)
(callback "set" get)
(def getDoubleMatrixAsList (callback "getDoubleMatrixAsList"))
(if-not (nil? getDoubleMatrixAsList)
	(throw (Exception. "getDoubleMatrixAsList not null!"))
)
(callback "set" get)

(def getFloatVector (callback "getFloatVector"))
(if-not (nil? getFloatVector)
	(throw (Exception. "getFloatVector not null!"))
)
(callback "set" get)
(def getFloatVectorAsList (callback "getFloatVectorAsList"))
(if-not (nil? getFloatVectorAsList)
	(throw (Exception. "getFloatVectorAsList not null!"))
)
(callback "set" get)
(def getFloatMatrix (callback "getFloatMatrix"))
(if-not (nil? getFloatMatrix)
	(throw (Exception. "getFloatMatrix not null!"))
)
(callback "set" get)
(def getFloatMatrixAsList (callback "getFloatMatrixAsList"))
(if-not (nil? getFloatMatrixAsList)
	(throw (Exception. "getFloatMatrixAsList not null!"))
)
(callback "set" get)

(def getIntegerVector (callback "getIntegerVector"))
(if-not (nil? getIntegerVector)
	(throw (Exception. "getIntegerVector not null!"))
)
(callback "set" get)
(def getIntegerVectorAsList (callback "getIntegerVectorAsList"))
(if-not (nil? getIntegerVectorAsList)
	(throw (Exception. "getIntegerVectorAsList not null!"))
)
(callback "set" get)
(def getIntegerMatrix (callback "getIntegerMatrix"))
(if-not (nil? getIntegerMatrix)
	(throw (Exception. "getIntegerMatrix not null!"))
)
(callback "set" get)
(def getIntegerMatrixAsList (callback "getIntegerMatrixAsList"))
(if-not (nil? getIntegerMatrixAsList)
	(throw (Exception. "getIntegerMatrixAsList not null!"))
)
(callback "set" get)

(def getLongVector (callback "getLongVector"))
(if-not (nil? getLongVector)
	(throw (Exception. "getLongVector not null!"))
)
(callback "set" get)
(def getLongVectorAsList (callback "getLongVectorAsList"))
(if-not (nil? getLongVectorAsList)
	(throw (Exception. "getLongVectorAsList not null!"))
)
(callback "set" get)
(def getLongMatrix (callback "getLongMatrix"))
(if-not (nil? getLongMatrix)
	(throw (Exception. "getLongMatrix not null!"))
)
(callback "set" get)
(def getLongMatrixAsList (callback "getLongMatrixAsList"))
(if-not (nil? getLongMatrixAsList)
	(throw (Exception. "getLongMatrixAsList not null!"))
)
(callback "set" get)

(def getPercentVector (callback "getPercentVector"))
(if-not (nil? getPercentVector)
	(throw (Exception. "getPercentVector not null!"))
)
(callback "set" get)
(def getPercentVectorAsList (callback "getPercentVectorAsList"))
(if-not (nil? getPercentVectorAsList)
	(throw (Exception. "getPercentVectorAsList not null!"))
)
(callback "set" get)
(def getPercentMatrix (callback "getPercentMatrix"))
(if-not (nil? getPercentMatrix)
	(throw (Exception. "getPercentMatrix not null!"))
)
(callback "set" get)
(def getPercentMatrixAsList (callback "getPercentMatrixAsList"))
(if-not (nil? getPercentMatrixAsList)
	(throw (Exception. "getPercentMatrixAsList not null!"))
)
(callback "set" get)

(def getShortVector (callback "getShortVector"))
(if-not (nil? getShortVector)
	(throw (Exception. "getShortVector not null!"))
)
(callback "set" get)
(def getShortVectorAsList (callback "getShortVectorAsList"))
(if-not (nil? getShortVectorAsList)
	(throw (Exception. "getShortVectorAsList not null!"))
)
(callback "set" get)
(def getShortMatrix (callback "getShortMatrix"))
(if-not (nil? getShortMatrix)
	(throw (Exception. "getShortMatrix not null!"))
)
(callback "set" get)
(def getShortMatrixAsList (callback "getShortMatrixAsList"))
(if-not (nil? getShortMatrixAsList)
	(throw (Exception. "getShortMatrixAsList not null!"))
)
(callback "set" get)

(def getStringVector (callback "getStringVector"))
(if-not (nil? getStringVector)
	(throw (Exception. "getStringVector not null!"))
)
(callback "set" get)
(def getStringVectorAsList (callback "getStringVectorAsList"))
(if-not (nil? getStringVectorAsList)
	(throw (Exception. "getStringVectorAsList not null!"))
)
(callback "set" get)
(def getStringMatrix (callback "getStringMatrix"))
(if-not (nil? getStringMatrix)
	(throw (Exception. "getStringMatrix not null!"))
)
(callback "set" get)
(def getStringMatrixAsList (callback "getStringMatrixAsList"))
(if-not (nil? getStringMatrixAsList)
	(throw (Exception. "getStringMatrixAsList not null!"))
)
(callback "set" get)
