(defmacro defined [& var]
    `(try 
        (or 
            (boolean (resolve ~@var)) 
            (not (nil? (eval ~@var)))
        ) (catch Exception e# false)
    )
)

(println "getByte")
(if (defined 'getByte)
	(throw (Exception. "getByte already defined"))
)
(def getByte (callback "getByte"))
(def getByteType (class getByte))
(println getByteType)
(println getByte)
(if-not (= getByteType Byte)
	(throw (Exception. "getByte not Byte!"))
)
(callback "setByte" getByte)

(println "getByteVector")
(if (defined 'getByteVector)
	(throw (Exception. "getByteVector already defined"))
)
(def getByteVector (callback "getByteVector"))
(def getByteVectorType (class (get getByteVector 0)))
(println getByteVectorType)
(println getByteVector)
(if-not (= getByteVectorType Byte)
	(throw (Exception. "getByteVector not Byte!"))
)
(callback "setByteVector" getByteVector)

(println "getByteVectorAsList")
(if (defined 'getByteVectorAsList)
	(throw (Exception. "getByteVectorAsList already defined"))
)
(def getByteVectorAsList (callback "getByteVectorAsList"))
(def getByteVectorAsListType (class (get getByteVectorAsList 0)))
(println getByteVectorAsListType)
(println getByteVectorAsList)
(if-not (= getByteVectorAsListType Byte)
	(throw (Exception. "getByteVectorAsList not Byte!"))
)
(callback "setByteVectorAsList" getByteVectorAsList)

(println "getByteMatrix")
(if (defined 'getByteMatrix)
	(throw (Exception. "getByteMatrix already defined"))
)
(def getByteMatrix (callback "getByteMatrix"))
(def getByteMatrixType (class (get (get getByteMatrix 0) 0)))
(println getByteMatrixType)
(println getByteMatrix)
(if-not (= getByteMatrixType Byte)
	(throw (Exception. "getByteMatrix not Byte!"))
)
(callback "setByteMatrix" getByteMatrix)

(println "getByteMatrixAsList")
(if (defined 'getByteMatrixAsList)
	(throw (Exception. "getByteMatrixAsList already defined"))
)
(def getByteMatrixAsList (callback "getByteMatrixAsList"))
(def getByteMatrixAsListType (class (get (get getByteMatrixAsList 0) 0)))
(println getByteMatrixAsListType)
(println getByteMatrixAsList)
(if-not (= getByteMatrixAsListType Byte)
	(throw (Exception. "getByteMatrixAsList not Byte!"))
)
(callback "setByteMatrixAsList" getByteMatrixAsList)
